### PR TITLE
Plop generator for new component

### PR DESCRIPTION
**Pull request by olamothe**
This will allow developers to run a command line utility to choose their component name.

This will generate the necessary boilerplate to get started rapidly.

https://coveord.atlassian.net/browse/JSUI-926

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/97)

### CODE REVIEW

**Comment by Dominionized** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 105 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN7KfbdiRmDlpl2W83N:-KN7KfbeMCesftorxw1t:1813990853) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/README.md#L105)):*
> ```Markdown
>     * Plop will add your component to `./tsconfig.json`. This will make it so it's recognized by the project.
>     * Plop will create a new file under `./test/ui/{{your component name}}Test.ts`. This is a blank test file, and where you should add your UT.
>     * Pleop will reference your component in `./test/Test.ts`. This will build your test like the rest of the components.
> ```

There is a typleop :P

---

*[README.md, line 108 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN7KzOzm3ZljlUxD-h1:-KN7KzOzm3ZljlUxD-h2:1094471785) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/README.md#L108)):*
> ```Markdown
> 5. Now, make it work ! (your mileage may vary).
> 6. Add tests for your component
> 7. You should try to test all public API of your component : This means all public methods as well as all available options.
> ```

I would say : _'You should test the public API of your component in its entirety'_ or _'You should test the entire public API of your component.'_

---

*[plop/plopTemplates/plop.component.test.template.hbs, line 15 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN7MVZxdNbRUN4M12js:-KN7MVZyhVc0UNTlGIlw:-53845582) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/plop/plopTemplates/plop.component.test.template.hbs#L15)):*
> ```Handlebars
>     });
> 
>     it('should put test here', ()=>{
> ```

`() => {` (with spaces) unless you want the linter to complain :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/97)*

**Comment by Dominionized** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/97)*

**Comment by dms1lva** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/97#-:-KN7WyI9SSb2aWFmZqt3:1417088721)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[README.md, line 108 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN7KzOzm3ZljlUxD-h1:-KN918MQ3ZbyWZP9z8Wu:1315596160) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/README.md#L108)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> I would say : _'You should test the public API of your component in its entirety'_ or _'You should test the entire public API of your component.'_
</details>
I prefer 'You should test the entire public API of your component.'

---

*[plop/plopfile.js, line 71 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN91YRd_sRWbYezlpLb:-KN91YRd_sRWbYezlpLc:-545757047) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/plop/plopfile.js#L71)):*
> ```JavaScript
>       let actions = [];
>       data.cmpName = plop.renderString('{{pascalCase cmpName}}', data);
>       console.log(data.cmpName);
> ```

Remove console.log?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/97)*

**Comment by Dominionized** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[plop/plopfile.js, line 71 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN91YRd_sRWbYezlpLb:-KNCpuWL-JKE05dU6p-3:872515622) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/plop/plopfile.js#L71)):*
<details><summary><i>Previously, mcarpentierCoveo (Mathieu Carpentier) wrote…</i></summary>
> Remove console.log?
</details>
It might actually be nice seeing a confirmation for the component's name though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/97)*

**Comment by olamothe** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 105 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN7KfbdiRmDlpl2W83N:-KNDhxiCzji5bhO1xj8v:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/README.md#L105)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> There is a typleop :P
</details>
Done.

---

*[README.md, line 108 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN7KzOzm3ZljlUxD-h1:-KNDhy4lqrf_-TNU4F-o:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/README.md#L108)):*
<details><summary><i>Previously, mcarpentierCoveo (Mathieu Carpentier) wrote…</i></summary>
> I prefer 'You should test the entire public API of your component.'
</details>
Done.

---

*[plop/plopfile.js, line 71 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN91YRd_sRWbYezlpLb:-KNDiBdwE7yfS48DtEK2:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/plop/plopfile.js#L71)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> It might actually be nice seeing a confirmation for the component's name though
</details>
Done.

---

*[plop/plopTemplates/plop.component.test.template.hbs, line 15 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/97#-KN7MVZxdNbRUN4M12js:-KNDiFFPOoj51lD1rLnF:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/459f8a258efe834750187d328905e5377a2925b3/plop/plopTemplates/plop.component.test.template.hbs#L15)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> `() => {` (with spaces) unless you want the linter to complain :P
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/97)*

**Pull request merged**
