### PR TITLE
[hotfix] Fixes the typo

### PR DESCRIPTION
**Pull request by npushkarskii**
This PR fixes the typo when some words start with a spoken "h" sound.

[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

### CODE REVIEW

**Review by mrrajamanickam-coveo — APPROVED** [review]

**Comment by npushkarskii** [comment]
hey @mrrajamanickam-coveo , thx for approving this PR! Could you plz merge it? I don't have enough access rights to do so 🤗

**Review by btaillon-coveo — APPROVED** [review]

**Comment by npushkarskii** [comment]
or maybe @btaillon can help me with merging this one 😋

**Comment by louis-bompart** [comment]
@nikmarjanovic I'll merge it, please provide a Jira for this one :)

**Comment by npushkarskii** [comment]
> @nikmarjanovic I'll merge it, please provide a Jira for this one :)

That was another Nik 😉
Here's a JIRA ticket https://coveord.atlassian.net/browse/DOC-12899

**Comment by louis-bompart** [comment]
> > @nikmarjanovic I'll merge it, please provide a Jira for this one :)
> 
> That was another Nik 😉 Here's a JIRA ticket https://coveord.atlassian.net/browse/DOC-12899

derp x)

**Pull request merged**
