### PR TITLE
JSUI-2843 Facet UA State Position should be Undefined and not Null by default

### PR DESCRIPTION
**Pull request by ThibodeauJF**
https://coveord.atlassian.net/browse/JSUI-2843

TIL Parameter is removed when undefined but not when null :/ 

[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

### CODE REVIEW

**Comment by olamothe** [comment]
What do you mean "removed" ? 
From where ?

**Comment by ThibodeauJF** [comment]
@olamothe from the request

**Comment by olamothe** [comment]
So the UI code removes the param before sending it? 

Is it intended ...?

**Comment by ThibodeauJF** [comment]
@olamothe Yes https://github.com/coveo/search-ui/blob/master/src/rest/SearchEndpoint.ts#L200

**Pull request merged**
