### PR TITLE
Jsui 902

### PR DESCRIPTION
**Pull request by dms1lva**
IE11 doesn't support CustomEvent. Added a polyfill to make sure window.CustomEvent and CustomEvent is defined.

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/57)

### CODE REVIEW

**Comment by olamothe** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/misc/CustomEventPolyfill.ts, line 11 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/57#-KLwLBH5_3qWP8jHhXMw:-KLwLBH5_3qWP8jHhXMx:-327107744) ([raw file](https://github.com/coveo/search-ui/blob/d7d20b3faab28e906a8e11f2619c36ec1d59d9ce/src/misc/CustomEventPolyfill.ts#L11)):*
> ```XML
>   }
> 
>   let CustomEvent = (event, params) => {
> ```

It's from mdn documentation, right ? I would add a comment that explain that + the link.

---

*[src/misc/CustomEventPolyfill.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/57#-KLwLADAiYh74LGBHVb_:-KLwLADAiYh74LGBHVba:1364413647) ([raw file](https://github.com/coveo/search-ui/blob/d7d20b3faab28e906a8e11f2619c36ec1d59d9ce/src/misc/CustomEventPolyfill.ts#L21)):*
> ```XML
> 
>   window.CustomEvent = CustomEvent;
> }
> ```

Newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/57#-:-KLwLL8PugHGUyFZVE_p:1417088721)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/misc/CustomEventPolyfill.ts, line 11 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/57#-KLwLBH5_3qWP8jHhXMw:-KLwMF2ebmM_aTDVdCpn:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/d7d20b3faab28e906a8e11f2619c36ec1d59d9ce/src/misc/CustomEventPolyfill.ts#L11)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> It's from mdn documentation, right ? I would add a comment that explain that + the link.
</details>
Done.

---

*[src/misc/CustomEventPolyfill.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/57#-KLwLADAiYh74LGBHVb_:-KLwMFWfzR_NZrXZzkdl:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/d7d20b3faab28e906a8e11f2619c36ec1d59d9ce/src/misc/CustomEventPolyfill.ts#L21)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Newline
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/57)*

**Comment by olamothe** [comment]
Run linter then :shipit: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/misc/CustomEventPolyfill.ts, line 2 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/57#-KLwYRzNU6dnmbUY7Z1l:-KLwYRzNU6dnmbUY7Z1m:1791009041) ([raw file](https://github.com/coveo/search-ui/blob/d51b496673a8499756a46e383226d28176cfcae0/src/misc/CustomEventPolyfill.ts#L2)):*
> ```XML
> 
> //CustomEvent polyfill from MDN
> ```

Space after // (try to run npm build, the linter will most likely complain)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/57#-:-KLwYMlu0RWMYp0CwjxH:-1696458086)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/misc/CustomEventPolyfill.ts, line 2 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/57#-KLwYRzNU6dnmbUY7Z1l:-KLwZHnUjXbI-fn6Ysa7:1546269814) ([raw file](https://github.com/coveo/search-ui/blob/d51b496673a8499756a46e383226d28176cfcae0/src/misc/CustomEventPolyfill.ts#L2)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Space after // (try to run npm build, the linter will most likely complain)
</details>
Wondering if we could run prettify when the dev server recompiles

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/57)*

**Pull request merged**
