### PR TITLE
JSUI 826

### PR DESCRIPTION
**Pull request by mcarpentierCoveo**
I removed the enableTopQueryAddon option from the Omnibox and used the alias from #26 to keep the backward compatibility.

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/27)

### CODE REVIEW

**Comment by olamothe** [comment]
:lgtm:

<details><summary><i>Previously, mcarpentierCoveo (Mathieu Carpentier) wrote…</i></summary>
> #### JSUI 826
> 
> I removed the enableTopQueryAddon option from the Omnibox and used the alias from #26 to keep the backward compatibility.
> 
> 
> 
</details>


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Omnibox/Omnibox.ts, line 99 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/27#-KJkJ9Ixjbzm5vTpqUGY:-KJkJ9Ixjbzm5vTpqUGZ:-560319179) ([raw file](https://github.com/coveo/search-ui/blob/0c9d25b6463ef8ff000712850f2791d62c0bc08e/src/ui/Omnibox/Omnibox.ts#L99)):*
> ```XML
>      * Default value is false
>      */
>     enableRevealQuerySuggestAddon: ComponentOptions.buildBooleanOption({ defaultValue: false, alias: 'data-enable-top-query-addon' }),
> ```

Same comment as the one for your PR about aliases : this should be the "non-markup" name ( `enableTopQueryAddon`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/27#-:-KJkJKDAeq5ubG4LWHlP:1417088721)*

**Comment by dms1lva** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/27)*

**Comment by dms1lva** [comment]
:lgtm:

<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/27#-:-KJkKazN1X3df_jZQBQi:980077401)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Omnibox/Omnibox.ts, line 99 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/27#-KJkJ9Ixjbzm5vTpqUGY:-KJkT0W_W2bDV1kBuuR6:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/0c9d25b6463ef8ff000712850f2791d62c0bc08e/src/ui/Omnibox/Omnibox.ts#L99)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Same comment as the one for your PR about aliases : this should be the "non-markup" name ( `enableTopQueryAddon`)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/27)*

**Pull request merged**
