### PR TITLE
Jsui 909

### PR DESCRIPTION
**Pull request by mcarpentierCoveo**
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/64)

### CODE REVIEW

**Comment by olamothe** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Analytics/AnalyticsActionListMeta.ts, line 443 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/64#-KM11lRgjXiHiHi9lt-5:-KM0zSEC9D_2GsTQydn5:1430591685) ([raw file](https://github.com/coveo/search-ui/blob/d215631f14bd5a0db01d04a72291b743d131e75a/src/ui/Analytics/AnalyticsActionListMeta.ts#L443)):*
> ```XML
>   },
>   recommendation: <IAnalyticsActionCause>{
>     name: 'recommendation',
> ```

The values we set here have a pretty big impact. For example, I'm pretty sure we don't want the `type` to be the same as the `name`.
And if we have to change this in the future this might be painful/annoying and break stuff.

I might be wrong though. 
I'll open a mail thread with the required people.

---

*[src/ui/Recommendation/Recommendation.ts, line 114 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/64#-KM12rzZxtGZr0Sd9N71:-KM12rz_-EBW8EsIf-hV:312188751) ([raw file](https://github.com/coveo/search-ui/blob/d215631f14bd5a0db01d04a72291b743d131e75a/src/ui/Recommendation/Recommendation.ts#L114)):*
> ```XML
>       this.mainInterfaceQuery = args;
>       this.mainQuerySearchUID = args.results.searchUid;
>       this.usageAnalytics.logSearchEvent(analyticsActionCauseList.recommendation, {});
> ```

Add the `<IAnalyticsNoMeta>` generic type on the method call so we break the build if we need to change this in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/64)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Analytics/AnalyticsActionListMeta.ts, line 443 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/64#-KM11lRgjXiHiHi9lt-5:-KM9x2vfOGAQlaMPKGX7:2128016620) ([raw file](https://github.com/coveo/search-ui/blob/d215631f14bd5a0db01d04a72291b743d131e75a/src/ui/Analytics/AnalyticsActionListMeta.ts#L443)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> The values we set here have a pretty big impact. For example, I'm pretty sure we don't want the `type` to be the same as the `name`.
> And if we have to change this in the future this might be painful/annoying and break stuff.
> 
> I might be wrong though. 
> I'll open a mail thread with the required people.
> 
</details>
For the recommendation document open, it's supposed to be 'recommendationOpen'. (View the comments in https://coveord.atlassian.net/browse/JSUI-909)
For the recommendation search, Richard said that 'recommendation' was ok.

---

*[src/ui/Recommendation/Recommendation.ts, line 114 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/64#-KM12rzZxtGZr0Sd9N71:-KM9xekIs8rqKkXG4-5o:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/d215631f14bd5a0db01d04a72291b743d131e75a/src/ui/Recommendation/Recommendation.ts#L114)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Add the `<IAnalyticsNoMeta>` generic type on the method call so we break the build if we need to change this in the future.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/64)*

**Comment by mcarpentierCoveo** [comment]
I checked in `Coveo - Dev` and even if the second click event is 'canceled' in the console. It is logged in the analytics.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/64#-:-KM9xzF5Og0QVwEx7V8S:462692720)*

**Comment by olamothe** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[test/ui/RecommendationAnalyticsClientTest.ts, line 27 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/64#-KMA-Q0Yapxj0L5kyG1r:-KMA-Q0Yapxj0L5kyG1s:-1472659580) ([raw file](https://github.com/coveo/search-ui/blob/2950d1ee082ade5164f779918bb00a54174c0e5e/test/ui/RecommendationAnalyticsClientTest.ts#L27)):*
> ```XML
>       spyOn(client, 'pushClickEvent');
>       client.logClickEvent(analyticsActionCauseList.documentOpen, {}, FakeResults.createFakeResult('foo'), document.createElement('div'));
>       expect((<any>client).pushClickEvent).toHaveBeenCalledWith(analyticsActionCauseList.recommendationOpen, jasmine.any(Object), jasmine.any(Object), jasmine.any(HTMLElement));
> ```

instead of `jasmine.any(HTMLElement)` couldn't it check that it's the correctly created `document.createElement('div')` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/64)*

**Comment by olamothe** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/64#-:-KMA-hLavLc-ZZ6jgFNW:1417088721)*

**Comment by dms1lva** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/64#-:-KMA5cTAzSTs7_tSlL-d:1417088721)*

**Comment by olamothe** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/64)*

**Pull request merged**
