### PR TITLE
Fix/snow 249 show more submit

### PR DESCRIPTION
**Pull request by dguerinCoveo**
My bad, just realized the bug was also present in the Dynamic Facet Header Button. 

SNOW-249

[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

### CODE REVIEW

**Comment by dguerinCoveo** [comment]
The cause of the bug is the same as for the ShowMoreLessButton: 
#1530

**Comment by olamothe** [comment]
@dguerinCoveo : The jira number SNOW-249 seems kind of unrelated ? It's about test.
Which one would be the correct jira ticket ?

We need this to be able to merge correctly.

**Comment by olamothe** [comment]
SNOW-349 ?

**Comment by dguerinCoveo** [comment]
My bad. Yes exactly

**Pull request merged**
