### PR TITLE
Jsui 827

### PR DESCRIPTION
**Pull request by fgagnoncoveo**
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/25)

### CODE REVIEW

**Comment by Dominionized** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Quickview/QuickviewDocument.ts, line 163 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/25#-KJkExOvS9pY7NusGEEO:-KJkExOvS9pY7NusGEEP:656220783) ([raw file](https://github.com/coveo/search-ui/blob/5c59a4843d38955de6d90d77bf00e853712e3ffa/src/ui/Quickview/QuickviewDocument.ts#L163)):*
> ```XML
> 
>   private renderErrorReport(iframe: HTMLIFrameElement, errorStatus: number) {
>     let errorString = "";
> ```

SINGLE QUOTES PLZ <3

---

*[strings/strings.json, line 2157 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/25#-KJkFKOmiW-oEFbbUiby:-KJkFKOmiW-oEFbbUibz:-1324163165) ([raw file](https://github.com/coveo/search-ui/blob/5c59a4843d38955de6d90d77bf00e853712e3ffa/strings/strings.json#L2157)):*
> ```JSON
>   "NoQuickview": {
>     "en": "The Quick View for this document is unavailable",
>     "fr": "Le Coup D'Oeil pour ce document n'est pas disponible"
> ```

Kinda nitpicky, but use this : Œ
Le Coup d'Œil

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/25)*

**Comment by Dominionized** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/25)*

**Comment by olamothe** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Quickview/QuickviewDocument.ts, line 163 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/25#-KJkExOvS9pY7NusGEEO:-KJkJuMOIZNp669E0nOJ:264272871) ([raw file](https://github.com/coveo/search-ui/blob/5c59a4843d38955de6d90d77bf00e853712e3ffa/src/ui/Quickview/QuickviewDocument.ts#L163)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> SINGLE QUOTES PLZ <3
</details>
Try to always run the prettify task before submitting (it's automatically run with `npm run build` or `gulp`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/25)*

**Comment by olamothe** [comment]
:lgtm:

<details><summary><i>Previously, fgagnoncoveo wrote…</i></summary>
> #### Jsui 827
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/25#-:-KJkK5ZfNxZyXx5xj73f:1417088721)*

**Comment by fgagnoncoveo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[strings/strings.json, line 2157 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/25#-KJkFKOmiW-oEFbbUiby:-KJpRYqKNMo-XFo38OdD:1652796818) ([raw file](https://github.com/coveo/search-ui/blob/5c59a4843d38955de6d90d77bf00e853712e3ffa/strings/strings.json#L2157)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Kinda nitpicky, but use this : Œ
> Le Coup d'Œil
</details>
I used the spelling used in the other strings for the sake of consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/25)*

**Pull request merged**
