### PR TITLE
Jsui 929

### PR DESCRIPTION
**Pull request by dms1lva**
The button boundaries weren't updated when moving it, only on initialization. Since the facet dropdown is hidden on load if the screen is too small, the boundaries were set to 0 and the slider button would immediately move to the far left on click. It would also have weird behaviour when the size of the slider would change.

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/85)

### CODE REVIEW

**Comment by mcarpentierCoveo** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/85)*

**Comment by olamothe** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[sass/_ResponsiveFacets.scss, line 34 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/85#-KMZyXdze9hB2J8DbWDr:-KMZyXdze9hB2J8DbWDs:1470365477) ([raw file](https://github.com/coveo/search-ui/blob/aa65f03de138f40aefd051bb5af4ac78fc59c574/sass/_ResponsiveFacets.scss#L34)):*
> ```SCSS
>     }
>     
>     .CoveoFacet, .CoveoFacetSlider, .CoveoFacetRange {
> ```

I guess you should also add `.CoveoHierarchicalFacet` here.

---

*[src/ui/Misc/Slider.ts, line 652 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/85#-KM_GfHXZsFx6IzJIG4i:-KM_GfHY2-RYWEoJS0J_:-224466844) ([raw file](https://github.com/coveo/search-ui/blob/aa65f03de138f40aefd051bb5af4ac78fc59c574/src/ui/Misc/Slider.ts#L652)):*
> ```XML
> 
>   public draw(data: ISliderGraphData[] = this.oldData) {
>     if (data && !this.root.hasClass('coveo-small-search-interface')) {
> ```

Shouldn't this use the available method on the SearchInterface to detect the small search interface ?

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 150 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/85#-KM_Gmx09IXS6vQCCfHu:-KM_Gmx09IXS6vQCCfHv:317164883) ([raw file](https://github.com/coveo/search-ui/blob/aa65f03de138f40aefd051bb5af4ac78fc59c574/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L150)):*
> ```XML
> 
>   private positionPopup() {
>     let facetList = this.dropdownContent.findAll('.CoveoFacet, .CoveoFacetSlider, .CoveoFacetRange');
> ```

HierarchicalFacet here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/85)*

**Comment by olamothe** [comment]
:lgtm:

Fix issue and :shipit: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/85#-:-KM_Gto86u_DOZNc_fEe:227596891)*

**Comment by dms1lva** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[sass/_ResponsiveFacets.scss, line 34 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/85#-KMZyXdze9hB2J8DbWDr:-KMdiF4m9AObrqu3xNOa:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/aa65f03de138f40aefd051bb5af4ac78fc59c574/sass/_ResponsiveFacets.scss#L34)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> I guess you should also add `.CoveoHierarchicalFacet` here.
</details>
Done.

---

*[src/ui/Misc/Slider.ts, line 652 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/85#-KM_GfHXZsFx6IzJIG4i:-KMdiJdAvGZDJZ9Twpf5:1659566679) ([raw file](https://github.com/coveo/search-ui/blob/aa65f03de138f40aefd051bb5af4ac78fc59c574/src/ui/Misc/Slider.ts#L652)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Shouldn't this use the available method on the SearchInterface to detect the small search interface ?
</details>
That was in another PR! But I just merged master so here it is B-)

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 150 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/85#-KM_Gmx09IXS6vQCCfHu:-KMdiaOKV3X9xPihAc3S:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/aa65f03de138f40aefd051bb5af4ac78fc59c574/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L150)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> HierarchicalFacet here too.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/85)*

**Pull request merged**
