### PR TITLE
Jsui 832 - fix popup position when scrolling

### PR DESCRIPTION
**Pull request by dms1lva**
Changed popup css position property from `absolute` to `fixed`. We were using viewport coordinates to set the position of the popup, so we need to position it relative to the viewport also.

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/24)

### CODE REVIEW

**Comment by mcarpentierCoveo** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/24)*

**Comment by Dominionized** [comment]
:lgtm:

<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> #### Jsui 832 \- fix popup position when scrolling
> 
> Changed popup css position property from `absolute` to `fixed`. We were using viewport coordinates to set the position of the popup, so we need to position it relative to the viewport also.
> 
> 
> 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/24#-:-KJkGuX47Gx1Phi1JpQ1:1417088721)*

**Comment by olamothe** [comment]
:lgtm:

<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> :lgtm:
</details>


---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/24#-:-KJkGoAphIy-Cv6BpizQ:980077401)*

**Comment by Dominionized** [comment]
Reviewed 1 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/24)*

**Pull request merged**
