### PR TITLE
JSUI-869 - Tab/Keyboard navigation

### PR DESCRIPTION
**Pull request by Dominionized**
Early pull request.

This implements keyboard navigation in the JSUI. Instead of using the mouse, elements in the page are now focusable in sequence using the Tab key. Some components have partial or no support, especially those which are used less often, but currently most of the default search interface is usable with a keyboard.

[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/123)

### CODE REVIEW

**Comment by dms1lva** [comment]
Would it be possible to not have to tab twice on the facet checkboxes? Also, I'm wondering if it could be helpful to have a way to go from the facet to the search results.

---

Reviewed 25 of 26 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/123#-:-KOBRCR3ixxFFYjcsQpr:-189987351)*

**Comment by Dominionized** [comment]
Yeah, for the facets, I know it isn't really optimal. I was torn between doing this (tabbing between select and exclude) and having separate hotkeys for select and exclude. Maybe I could also put a hotkey to go to the search results directly, but at this point it's not as much a question of accessibility rather than power-user friendliness :P

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/123#-:-KOBeqbs3OkK0vloh2uF:-2077100515)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 24 of 26 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/123)*

**Comment by mcarpentierCoveo** [comment]
Is it normal that you cannot use tab to get out of the Searchbox?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/123#-:-KORSeldSRU9nzB9z0FZ:b-6p6gdt)*

**Comment by mcarpentierCoveo** [comment]
NVM I didn't update npm :facepalm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/123#-:-KORTsKn_rfwVlHme9nF:bx2u3u8)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/123)*

**Comment by olamothe** [comment]
:lgtm:

Looks okay. I would add a couple UT for the really important elements to check if the tab index is there (Result link, facets, FieldTable, Pager, etc.)

Don't need to test *all* of them, but the really important one should be tested.

---

Reviewed 23 of 26 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/123#-:-KPDYVkkzs1FwfdWH6f2:b-i38v2k)*

**Pull request merged**
