### PR TITLE
attribute options before Coveo.options

### PR DESCRIPTION
**Pull request by dms1lva**
[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)
https://coveord.atlassian.net/browse/JSUI-1001

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/126)

### CODE REVIEW

**Comment by Dominionized** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Base/ComponentOptions.ts, line 276 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/126#-KOGLkTMpDKjQtTjHTsf:-KOGLkTMpDKjQtTjHTsg:489086917) ([raw file](https://github.com/coveo/search-ui/blob/af6418b129ab1ea25090d6be95b6712232bb142e/src/ui/Base/ComponentOptions.ts#L276)):*
> ```XML
>           console.log(componentID + '.' + name + ' : ' + optionDefinition.deprecated);
>         }
>       } else if (values[name] != undefined) {
> ```

Can you use !== instead here ? Or could it be null ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/126)*

**Comment by Dominionized** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/126#-:-KOGLzz0-bXwhPqrSNE1:1417088721)*

**Comment by Dominionized** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/126)*

**Comment by dms1lva** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Base/ComponentOptions.ts, line 276 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/126#-KOGLkTMpDKjQtTjHTsf:-KOGOxV62_i_UoLWjfDf:1818851215) ([raw file](https://github.com/coveo/search-ui/blob/af6418b129ab1ea25090d6be95b6712232bb142e/src/ui/Base/ComponentOptions.ts#L276)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Can you use !== instead here ? Or could it be null ?
</details>
Well these values come from initialization using `Coveo.options`, so they could be null.. anyways I think it's ok to not set the option to a null value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/126)*

**Pull request merged**
