### PR TITLE
JSUI-3224 Improve analytics log function types

### PR DESCRIPTION
**Pull request by samisayegh**
This PR is a direct clone of [Tom's submission](https://github.com/coveo/search-ui/pull/1723) to have the changes run on CI, and ensure the changes are associated with a jira.

[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

### CODE REVIEW

**Comment by olamothe** [comment]
Looking at the build, it seems this will require some tweaks in the generated definition in order to be TypeScript 1.x compliant 🤔

**Comment by ThibodeauJF** [comment]
Typescript V1 does not allow for generic defaults, which were introduced in the v2.
I guess we can strip them, like it's the case here: https://github.com/coveo/search-ui/pull/1260/files

Wouldn't that break for people using V1 though, since they will be forced to define that generic or they'll see a compilation error?

**Comment by tcarrio** [comment]
@ThibodeauJF What versions of TypeScript v1 are supported? I'd be interested in testing out the changes with non-default generics. With this change provide as much type safety as possible based on the nested methods as opposed to the `any` provided by a non-extended generic type.

Without the default value, it would be inferred from the passed value. In which case, simply removing the default value may be enough here.

**Comment by ThibodeauJF** [comment]
@tcarrio `1.8.10`

**Comment by tcarrio** [comment]
Looks like your commit has passed CI, thanks for getting that update in :+1:

**Review by ThibodeauJF — APPROVED** [review]

**Review by olamothe — APPROVED** [review]

**Comment by ThibodeauJF** [comment]
@tcarrio Thanks for the improvements 😄 
It will be available in the next JSUI release, which we do monthly https://docs.coveo.com/en/328/javascript-search-framework/javascript-search-framework-release-notes

**Pull request merged**
