### PR TITLE
Jsui 846

### PR DESCRIPTION
**Pull request by mcarpentierCoveo**
https://coveord.atlassian.net/browse/JSUI-846

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/34)

### CODE REVIEW

**Comment by olamothe** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Omnibox/Omnibox.ts, line 471 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/34#-KKsR5qNn7o_nRBn9x-K:-KKsR5qNn7o_nRBn9x-L:818826451) ([raw file](https://github.com/coveo/search-ui/blob/fc8442a60f1ff267f53856fd37ea6f3ec487c4fc/src/ui/Omnibox/Omnibox.ts#L471)):*
> ```XML
>       this.queryController.executeQuery({
>         searchAsYouType: searchAsYouType,
>         logInActionsHistory: true
> ```

Why do we need to log only queries coming from the search box ? 

Is it a requirement by the reveal team ?

If yes, I would add a comment (probably in the query controller) as to why this is like this.


Also, there is already an `origin` property on the `IQueryOptions`. Could we use this instead to discriminate for components that are `instance of Querybox` or `Omnibox`

---

*[test/ui/RecommendationTest.ts, line 53 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/34#-KKsRqpeRTzN2ttpTwVM:-KKsRqpeRTzN2ttpTwVN:-1115397868) ([raw file](https://github.com/coveo/search-ui/blob/fc8442a60f1ff267f53856fd37ea6f3ec487c4fc/test/ui/RecommendationTest.ts#L53)):*
> ```XML
>       test = Mock.optionsSearchInterfaceSetup<Recommendation, IRecommendationOptions>(Recommendation, options);
>       let simulation = Simulate.query(mainSearchInterface.env);
>       expect(test.cmp.queryController.executeQuery).toHaveBeenCalled();
> ```

Hum is it me or this test does not verify anything important ?

If that's the case, better to remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/34)*

**Comment by Dominionized** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/34)*

**Comment by mcarpentierCoveo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Omnibox/Omnibox.ts, line 471 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/34#-KKsR5qNn7o_nRBn9x-K:-KKtsGpqDfjPc0voVxV1:-213193102) ([raw file](https://github.com/coveo/search-ui/blob/fc8442a60f1ff267f53856fd37ea6f3ec487c4fc/src/ui/Omnibox/Omnibox.ts#L471)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Why do we need to log only queries coming from the search box ? 
> 
> Is it a requirement by the reveal team ?
> 
> If yes, I would add a comment (probably in the query controller) as to why this is like this.
> 
> 
> Also, there is already an `origin` property on the `IQueryOptions`. Could we use this instead to discriminate for components that are `instance of Querybox` or `Omnibox`
</details>
It's not a reveal requirement, but it was causing problems with the recommendation component, because the query would be logged twice. 
Also, it was logging the empty interface load query which I think is strange.

---

*[test/ui/RecommendationTest.ts, line 53 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/34#-KKsRqpeRTzN2ttpTwVM:-KKttTw-IAiLD0FzPJme:789368874) ([raw file](https://github.com/coveo/search-ui/blob/fc8442a60f1ff267f53856fd37ea6f3ec487c4fc/test/ui/RecommendationTest.ts#L53)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Hum is it me or this test does not verify anything important ?
> 
> If that's the case, better to remove it.
</details>
It makes sure that the component will work if coveoanalytics is undefined. 
I'm going to modify the test to make sure that the history sent is '[]' instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/34)*

**Comment by olamothe** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/34)*

**Pull request merged**
