### PR TITLE
Jsui 1000

### PR DESCRIPTION
**Pull request by fgagnoncoveo**
[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/134)

### CODE REVIEW

**Comment by Dominionized** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Base/ComponentOptions.ts, line 298 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOkgMjwKN0cgVFEBw3z:-KOkgMjxT4ehCLuA7ZSz:b-l4lt8n) ([raw file](https://github.com/coveo/search-ui/blob/a436a125d02564f8bdf3801a8536f3a6a1d98f88/src/ui/Base/ComponentOptions.ts#L298)):*
> ```XML
>       if (value != null) {
>         if (optionDefinition.validator && !optionDefinition.validator(value)) {
>           console.log('Option : ' + name + ' has invalid value : ' + value);
> ```

You should use `Assert.fail` instead. Also, I wouldn't put a ":" after Option

---

*[test/ui/ComponentOptionsTest.ts, line 283 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOkhyfGTfq1x65A2N88:-KOkhyfHXmtqXw8Cg7gH:bhthan) ([raw file](https://github.com/coveo/search-ui/blob/a436a125d02564f8bdf3801a8536f3a6a1d98f88/test/ui/ComponentOptionsTest.ts#L283)):*
> ```XML
>         });
>       });
> ```

I would add a test which verifies that passing an invalid value throws an exception

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by dms1lva** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 258 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOklSPjvk1QVBptwFFv:-KOklSPjvk1QVBptwFFw:b3are8m) ([raw file](https://github.com/coveo/search-ui/blob/5a76568e553433e3ca38b89d80d9ac38b9cbd6b0/test/ui/ComponentOptionsTest.ts#L258)):*
> ```XML
>           expect(initOptions).toEqual({ myAttr: 'baz foo' });
>         });
>         it('which validates a component option with the specified validator', function () {
> ```

() => {

---

*[test/ui/ComponentOptionsTest.ts, line 270 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOko90vUoqaNVgVN21p:-KOko90wtMhLGkZWAnmh:b-qk618m) ([raw file](https://github.com/coveo/search-ui/blob/5a76568e553433e3ca38b89d80d9ac38b9cbd6b0/test/ui/ComponentOptionsTest.ts#L270)):*
> ```XML
>           expect(initOptions).toEqual({ myAttr: 'baz' });
>         });
>         it('which validates a component option with the specified validator', function () {
> ```

Two tests with the same name :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Reviewed 2 of 2 files at r1, 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 283 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOkhyfGTfq1x65A2N88:-KOp-NRR_lXvwC1ixFWV:bxn910q) ([raw file](https://github.com/coveo/search-ui/blob/a436a125d02564f8bdf3801a8536f3a6a1d98f88/test/ui/ComponentOptionsTest.ts#L283)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> I would add a test which verifies that passing an invalid value throws an exception
</details>
Correction : an invalid value which is **non-required**

---

*[test/ui/ComponentOptionsTest.ts, line 258 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOklSPjvk1QVBptwFFv:-KOozPfR6F2Bv48pMYtg:b-2wlm24) ([raw file](https://github.com/coveo/search-ui/blob/5a76568e553433e3ca38b89d80d9ac38b9cbd6b0/test/ui/ComponentOptionsTest.ts#L258)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> () => {
</details>
Do we have a consensus on this ? Because for the moment, it's kind of all over the place in the codebase. I guess we could probably do a search and replace and add a linter rule to prevent the use of `function () {`. What do you think ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 258 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOklSPjvk1QVBptwFFv:-KOp1OBF6Eb0Y-5F4EYF:b8v9w7g) ([raw file](https://github.com/coveo/search-ui/blob/5a76568e553433e3ca38b89d80d9ac38b9cbd6b0/test/ui/ComponentOptionsTest.ts#L258)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Do we have a consensus on this ? Because for the moment, it's kind of all over the place in the codebase. I guess we could probably do a search and replace and add a linter rule to prevent the use of `function () {`. What do you think ?
</details>
If remember correctly, the consensus was that if the function doesn't need to have its own `this`, we should always use the phat arrow. Still agree on this? I don't know if a linter rule could take the use of this into account, maybe a custom one :new_moon_with_face: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ui/Base/ComponentOptions.ts, line 298 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOkgMjwKN0cgVFEBw3z:-KOp268w41jwMBf_9Vzx:b-8c8t4) ([raw file](https://github.com/coveo/search-ui/blob/a436a125d02564f8bdf3801a8536f3a6a1d98f88/src/ui/Base/ComponentOptions.ts#L298)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> You should use `Assert.fail` instead. Also, I wouldn't put a ":" after Option
</details>
After this morning's discussion,  
non-required option -> log an error
required option -> assert

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 258 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOklSPjvk1QVBptwFFv:-KOp3cYm-FZggm1RjfWZ:bc9wabg) ([raw file](https://github.com/coveo/search-ui/blob/5a76568e553433e3ca38b89d80d9ac38b9cbd6b0/test/ui/ComponentOptionsTest.ts#L258)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> If remember correctly, the consensus was that if the function doesn't need to have its own `this`, we should always use the phat arrow. Still agree on this? I don't know if a linter rule could take the use of this into account, maybe a custom one :new_moon_with_face: 
</details>
http://palantir.github.io/tslint/rules/only-arrow-functions/ :stuck_out_tongue_winking_eye: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 258 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOklSPjvk1QVBptwFFv:-KOp3i2uTzAhMU-9q_kZ:b-pd5y9d) ([raw file](https://github.com/coveo/search-ui/blob/5a76568e553433e3ca38b89d80d9ac38b9cbd6b0/test/ui/ComponentOptionsTest.ts#L258)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> http://palantir.github.io/tslint/rules/only-arrow-functions/ :stuck_out_tongue_winking_eye: 
</details>
Actually, I can't see any scenario where the the non-arrow function would be useful

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 258 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOklSPjvk1QVBptwFFv:-KOp4Awmha6lm6rRmAUi:b-jcgj8h) ([raw file](https://github.com/coveo/search-ui/blob/5a76568e553433e3ca38b89d80d9ac38b9cbd6b0/test/ui/ComponentOptionsTest.ts#L258)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Actually, I can't see any scenario where the the non-arrow function would be useful
</details>
Ya, it should be super rare, if it happens disabling the rule for that code block is not too bad I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 232 \[r5\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOq9cX3Cime8d7yhFBr:-KOq9cX3Cime8d7yhFBs:b-jyskjo) ([raw file](https://github.com/coveo/search-ui/blob/3036972cc78d3896220877c944d75a4e64adf533/test/ui/ComponentOptionsTest.ts#L232)):*
> ```XML
>             })
>           };
>           expect(() => { ComponentOptions.initComponentOptions(elem, { options, ID: 'fooID' }) }).toThrow();
> ```

You don't have to put the `{` and `}` when inlining arrow functions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Comment by Dominionized** [comment]
Guys, would this be ready to merge ? I would use it in my new feature if it was available.

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134#-:-KPNhxn_e0-7hlw37Qu1:b-c0k1r3)*

**Comment by olamothe** [comment]
I'll finish it.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134#-:-KPP4-H91xdV98iWRCue:bar4mj7)*

**Comment by olamothe** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/ui/Base/ComponentOptions.ts, line 298 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/134#-KOkgMjwKN0cgVFEBw3z:-KPP4dlO3JvoiCULgIX5:buf6j3o) ([raw file](https://github.com/coveo/search-ui/blob/a436a125d02564f8bdf3801a8536f3a6a1d98f88/src/ui/Base/ComponentOptions.ts#L298)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> After this morning's discussion,  
> non-required option -> log an error
> required option -> assert
</details>
That was my line of thinking back in the days, but this kind aggressive failing has some very bad drawbacks.

There is no end to the amount of bad customization/configuration that can be made, and by failing aggressively like this on initialization (because options are all parsed on initialization), the UI will fail 100% of the time anytime a single component is badly configured.

It's better to log an error here, and then the single component that is badly configured will not work, but at least 99% of the UI will still function properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/134)*

**Pull request merged**
