### PR TITLE
Jsui 838

### PR DESCRIPTION
**Pull request by fgagnoncoveo**
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/89)

### CODE REVIEW

**Comment by dms1lva** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/ui/ComponentOptionsTest.ts, line 7 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/89#-KMfFFkoVWjdk8X4X92T:-KMfFFkoVWjdk8X4X92U:451598342) ([raw file](https://github.com/coveo/search-ui/blob/7b95e904cbc4ef6a98cfaf01b1d3fc432efc9649/test/ui/ComponentOptionsTest.ts#L7)):*
> ```XML
>     describe('can build', () => {
>       it('a boolean option', function () {
>         var option = ComponentOptions.buildBooleanOption();
> ```

Should use `let` everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/89)*

**Comment by olamothe** [comment]
Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[test/ui/ComponentOptionsTest.ts, line 3 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/89#-KMicuErWhDgvx67fqqV:-KMicuEskQaR1XlFIYQk:1627345278) ([raw file](https://github.com/coveo/search-ui/blob/7b95e904cbc4ef6a98cfaf01b1d3fc432efc9649/test/ui/ComponentOptionsTest.ts#L3)):*
> ```XML
> /// <reference path="../Test.ts" />
> module Coveo {
>   describe('ComponentOptions', () => {
> ```

Looks okay. But is it me or the different parameters we can pass when loading an option are not very well tested ?

For example, defaultValue, which acts differently depending if it's a list, an object, or a simple number.
Same for defaultFunction, postProcessing, etc.

---

*[test/ui/ComponentOptionsTest.ts, line 183 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/89#-KMidYav47bDQn596MHs:-KMidYav47bDQn596MHt:822627007) ([raw file](https://github.com/coveo/search-ui/blob/7b95e904cbc4ef6a98cfaf01b1d3fc432efc9649/test/ui/ComponentOptionsTest.ts#L183)):*
> ```XML
>       });
>       describe('initComponentOptions', () => {
>         it('which initializes the options of a component', function () {
> ```

I would like to see more test like this one since this is what all component use 99% of the time.

Just different component options definitions, with the different parameters (defaultFunction, defaultValue, postProcessing etc..), and check the the initialized options match what we expect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/89)*

**Comment by olamothe** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/89)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/89)*

**Comment by olamothe** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/89)*

**Comment by olamothe** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/89#-:-KMybccy5RGWBMXeMGFQ:980077423)*

**Pull request merged**
