### PR TITLE
Jsui 897

### PR DESCRIPTION
**Pull request by mcarpentierCoveo**
Fixed multiple bugs in the hierarchical facets

- Hierarchical facets were not collapsing
- HierarchicalFacetSearch: Select all now selects children as well
- Hierarchical facets were not showing the right amount of values

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/55)

### CODE REVIEW

**Comment by olamothe** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts, line 4 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/55#-KLwIjLYZ44Z8dCBfIcx:-KLwIjLYZ44Z8dCBfIcy:-23390778) ([raw file](https://github.com/coveo/search-ui/blob/e51bc298f47c207fb5eac4bb97a7e54eaba49b9e/src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts#L4)):*
> ```XML
> 
> import {FacetSearch} from '../Facet/FacetSearch';
> import {HierarchicalFacet} from './HierarchicalFacet';
> ```

You can `import {HierarchicalFacet, IValueHierarchy} from HierarchicalFacet` instead of putting it on 2 separate lines 

---

*[src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts, line 30 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/55#-KLwJ12pIJxfgX_PHsrY:-KLwJ12qQTcZrp1XYReN:-1600034068) ([raw file](https://github.com/coveo/search-ui/blob/e51bc298f47c207fb5eac4bb97a7e54eaba49b9e/src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts#L30)):*
> ```XML
> 
>     var searchParameters = new FacetSearchParameters(this.facet);
>     searchParameters.nbResults = 1000;
> ```

Why 1000 ? Is it just an arbitrary big number ? If so, add a comment that explain it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/55#-:-KLwJ_JjatC6r7RzQqb-:1417088721)*

**Comment by mcarpentierCoveo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts, line 30 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/55#-KLwJ12pIJxfgX_PHsrY:-KLwMQTqb_uI6dGCJg0B:-502792457) ([raw file](https://github.com/coveo/search-ui/blob/e51bc298f47c207fb5eac4bb97a7e54eaba49b9e/src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts#L30)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Why 1000 ? Is it just an arbitrary big number ? If so, add a comment that explain it.
</details>
Probably, I copied it from the initial FacetSearch method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/55)*

**Comment by dms1lva** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/55)*

**Comment by dms1lva** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/55#-:-KLwyyxTyMImv_HGdgR9:1417088721)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts, line 4 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/55#-KLwIjLYZ44Z8dCBfIcx:-KM-NgL08sMknbxLYpCp:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/e51bc298f47c207fb5eac4bb97a7e54eaba49b9e/src/ui/HierarchicalFacet/HierarchicalFacetSearch.ts#L4)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> You can `import {HierarchicalFacet, IValueHierarchy} from HierarchicalFacet` instead of putting it on 2 separate lines 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/55)*

**Pull request merged**
