### PR TITLE
ResultsPerPage now hides on query error or no results. https://coveor…

### PR DESCRIPTION
**Pull request by fgagnoncoveo**
[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)
…d.atlassian.net/browse/JSUI-988

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/133)

### CODE REVIEW

**Comment by Dominionized** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sass/_ResultsPerPage.scss, line 2 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/133#-KOp41Omar6vIqyv-TaN:-KOp41Omar6vIqyv-TaO:bp4dpd0) ([raw file](https://github.com/coveo/search-ui/blob/a5dff83a823f3510653c08699c97ace921ef76d7/sass/_ResultsPerPage.scss#L2)):*
> ```SCSS
> .CoveoResultsPerPage {
>   margin-top: -10px;
> ```

`margin: -10px 15px 0 15px` would be cleaner IMO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/133)*

**Comment by Dominionized** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/133#-:-KOp4FWHqnl4xqKWYeoy:bnfp4nl)*

**Comment by Dominionized** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/133)*

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/Pager/ResultsPerPage.ts, line 40 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/133#-KOv6RGZzeVk2vLEJFfx:-KOv6RGZzeVk2vLEJFfy:b-h9yz1o) ([raw file](https://github.com/coveo/search-ui/blob/c75d7d013658cb061f5f4ec8125fc78f873dda15/src/ui/Pager/ResultsPerPage.ts#L40)):*
> ```XML
>   private ignoreNextQuerySuccess: boolean = false;
> 
>   private span: HTMLElement;
> ```

I think this could have a better name that explains what the span contains.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/133#-:-KOv7YmyZkPZ8-OXSD1Z:bnfp4nl)*

**Pull request merged**
