### PR TITLE
JSUI-953 – Incongruity in Responsive Facets between select and exclude

### PR DESCRIPTION
**Pull request by Dominionized**
https://coveord.atlassian.net/browse/JSUI-953

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/100)

### CODE REVIEW

**Comment by olamothe** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 137 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/100#-KN8bpnWUY2CJLHHjSDx:-KN8bpnXrrDZx5SGu6No:561040470) ([raw file](https://github.com/coveo/search-ui/blob/a7ecd3c458f8abda672dd065fa749ce2ea4d396b/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L137)):*
> ```XML
>     return !eventTarget.closest('coveo-facet-column') && !eventTarget.closest('coveo-facet-dropdown-header')
>       && this.searchInterface.isSmallInterface() && !eventTarget.closest('coveo-facet-settings-popup')
>       && !eventTarget.closest('coveo-facet-value');
> ```

Could we modify the `closest` function so it support multiple parameter ? (an array of classes).

And we could check all the classes at once.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100#-:-KN8c3eDVp4-ohcuQ3f6:1417088721)*

**Comment by olamothe** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 137 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/100#-KN8bpnWUY2CJLHHjSDx:-KN8pQNhD5hQlpr6CBCp:1614614450) ([raw file](https://github.com/coveo/search-ui/blob/a7ecd3c458f8abda672dd065fa749ce2ea4d396b/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L137)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Could we modify the `closest` function so it support multiple parameter ? (an array of classes).
> 
> And we could check all the classes at once.
</details>
About that, I just spoke with the UX guy and he agrees that it would be better if the facet dropdown would close only when clicking outside of it. Do you wanna do this here? I could make another PR for it, as you wish.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100)*

**Comment by Dominionized** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 137 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/100#-KN8bpnWUY2CJLHHjSDx:-KN8v7dtNSKb13MSFW-k:-1546482482) ([raw file](https://github.com/coveo/search-ui/blob/a7ecd3c458f8abda672dd065fa749ce2ea4d396b/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L137)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> About that, I just spoke with the UX guy and he agrees that it would be better if the facet dropdown would close only when clicking outside of it. Do you wanna do this here? I could make another PR for it, as you wish.
</details>
Oh, I thought it was the expected behaviour. The change I just made makes it do just that (the only way to detach is to click/touch outside)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 137 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/100#-KN8bpnWUY2CJLHHjSDx:-KN8wNrUyKY51fHqzi5k:-1185022062) ([raw file](https://github.com/coveo/search-ui/blob/a7ecd3c458f8abda672dd065fa749ce2ea4d396b/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L137)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Oh, I thought it was the expected behaviour. The change I just made makes it do just that (the only way to detach is to click/touch outside)
</details>
Great!! :tada: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100)*

**Comment by Dominionized** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 137 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/100#-KN8bpnWUY2CJLHHjSDx:-KNCoAjmWF0NZkjg5_-m:1787706374) ([raw file](https://github.com/coveo/search-ui/blob/a7ecd3c458f8abda672dd065fa749ce2ea4d396b/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L137)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> Great!! :tada: 
</details>
Although there might be a better way to do this... I might look into it. Maybe instead of searching for a closest element inside the panel, it would be better if I added a click listener on the outside overlay so whenever the user clicks on it, the panel gets closed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 137 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/100#-KN8bpnWUY2CJLHHjSDx:-KNCox3CETLcYGMMxh9W:-1101147114) ([raw file](https://github.com/coveo/search-ui/blob/a7ecd3c458f8abda672dd065fa749ce2ea4d396b/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L137)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Although there might be a better way to do this... I might look into it. Maybe instead of searching for a closest element inside the panel, it would be better if I added a click listener on the outside overlay so whenever the user clicks on it, the panel gets closed.
</details>
Ohh that sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100)*

**Comment by Dominionized** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 137 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/100#-KN8bpnWUY2CJLHHjSDx:-KND6LizZFzthN6pzEoX:-361910800) ([raw file](https://github.com/coveo/search-ui/blob/a7ecd3c458f8abda672dd065fa749ce2ea4d396b/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L137)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> Ohh that sounds good
</details>
Done. I think it's much cleaner like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/100)*

**Pull request merged**
