### PR TITLE
Jsui 753

### PR DESCRIPTION
**Pull request by mcarpentierCoveo**
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/38)

### CODE REVIEW

**Comment by olamothe** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sass/_ResultFrame.scss, line 3 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/38#-KLHbDg3oAjADppi3X4r:-KLHbDg3oAjADppi3X4s:-2078657551) ([raw file](https://github.com/coveo/search-ui/blob/7c7e7a23913aa585dcddaac4bb8be6306c82f89a/sass/_ResultFrame.scss#L3)):*
> ```SCSS
> .coveo-result-frame, .CoveoResult.coveo-result-frame {
>   margin-left: 0;
>   display: flex;
> ```

For every "flex" css property, we should be using the bourbon mixin.
It's something like `@include display('flex');` This will output vendor prefix accordingly.

http://bourbon.io/docs/#flexbox

---

*[templates/All/Default.html, line 3 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/38#-KLHbiVxCkDaOx77xned:-KLHbiVxCkDaOx77xnee:-1909226634) ([raw file](https://github.com/coveo/search-ui/blob/7c7e7a23913aa585dcddaac4bb8be6306c82f89a/templates/All/Default.html#L3)):*
> ```HTML
> <div class="coveo-result-frame">
>   <div class="coveo-result-row">
>     <div class="coveo-result-cell" style="flex-basis:85px; flex-grow: 0; flex-shrink: 0; text-align:center; padding-top:7px;">
> ```

Since those property are inline in order to be modified with the interface editor, will it still work ?

I'm pretty sure the `width` property is exposed in the interface editor, and this will cause issue (since we are now using flex-basis)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/38)*

**Comment by mcarpentierCoveo** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[sass/_ResultFrame.scss, line 3 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/38#-KLHbDg3oAjADppi3X4r:-KLIQmK4szg7lIajS_T7:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/7c7e7a23913aa585dcddaac4bb8be6306c82f89a/sass/_ResultFrame.scss#L3)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> For every "flex" css property, we should be using the bourbon mixin.
> It's something like `@include display('flex');` This will output vendor prefix accordingly.
> 
> http://bourbon.io/docs/#flexbox
</details>
Done.

---

*[templates/All/Default.html, line 3 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/38#-KLHbiVxCkDaOx77xned:-KLI8q2omoih6u5_I1td:-524256767) ([raw file](https://github.com/coveo/search-ui/blob/7c7e7a23913aa585dcddaac4bb8be6306c82f89a/templates/All/Default.html#L3)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Since those property are inline in order to be modified with the interface editor, will it still work ?
> 
> I'm pretty sure the `width` property is exposed in the interface editor, and this will cause issue (since we are now using flex-basis)
</details>
Yes, I made changes in the interface editor to use flex instead. 
https://bitbucket.org/coveord/jssearchlib/pull-requests/178/update-interfaceeditor-to-support-result/diff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/38)*

**Comment by dms1lva** [comment]
Reviewed 12 of 14 files at r1, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/38)*

**Comment by olamothe** [comment]
Reviewed 2 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/38)*

**Pull request merged**
