### PR TITLE
Jsui 834

### PR DESCRIPTION
**Pull request by fgagnoncoveo**
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/62)

### CODE REVIEW

**Comment by mcarpentierCoveo** [comment]
:lgtm: 

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Base/ComponentOptions.ts, line 38 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/62#-KM0BLLEBk3ShFQyej3M:-KM0BLLEBk3ShFQyej3N:32785118) ([raw file](https://github.com/coveo/search-ui/blob/fe42bcd7188f1411f4fd7f7c628859b1a450196c/src/ui/Base/ComponentOptions.ts#L38)):*
> ```XML
>   depend?: string;
>   priority?: number;
>   deprecated?: string;
> ```

I would make this option a boolean instead of a string.

---

*[src/ui/Facet/Facet.ts, line 131 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/62#-KM0BeGsi6UgyNqo-osm:-KM0BeGsi6UgyNqo-osn:945325643) ([raw file](https://github.com/coveo/search-ui/blob/fe42bcd7188f1411f4fd7f7c628859b1a450196c/src/ui/Facet/Facet.ts#L131)):*
> ```XML
>      * @deprecated This option is exposed for legacy reason, and the recommendation is to not use this option.
>      */
>     headerIcon: ComponentOptions.buildIconOption({ deprecated: 'This option is exposed for legacy reason, and the recommendation is to not use this option.' }),
> ```

I don't think we need to repeat what is already in the doc here.
`{ deprecated: true }` would be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/62#-:-KM0Adw1njFsQcWtT3UN:980077423)*

**Comment by olamothe** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Facet/Facet.ts, line 131 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/62#-KM0BeGsi6UgyNqo-osm:-KM0X9A40UgMv7JR4IfK:1239968362) ([raw file](https://github.com/coveo/search-ui/blob/fe42bcd7188f1411f4fd7f7c628859b1a450196c/src/ui/Facet/Facet.ts#L131)):*
<details><summary><i>Previously, mcarpentierCoveo (Mathieu Carpentier) wrote…</i></summary>
> I don't think we need to repeat what is already in the doc here.
> `{ deprecated: true }` would be enough.
</details>
This was my request actually (to make this a string and to repeat the message).

My reasoning was that I wanted to be able to output a useful error message in the developer console when a deprecated option is used.

Otherwise someone might use a deprecated option, but might not know why it's not good to use it, or what to use instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/62)*

**Comment by olamothe** [comment]
:lgtm: Ship it

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/62#-:-KM0Xy9DZesLBZLgIT3T:-1851419872)*

**Comment by mcarpentierCoveo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Facet/Facet.ts, line 131 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/62#-KM0BeGsi6UgyNqo-osm:-KM0ag9AVvEz-oqCmovQ:756498949) ([raw file](https://github.com/coveo/search-ui/blob/fe42bcd7188f1411f4fd7f7c628859b1a450196c/src/ui/Facet/Facet.ts#L131)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> This was my request actually (to make this a string and to repeat the message).
> 
> My reasoning was that I wanted to be able to output a useful error message in the developer console when a deprecated option is used.
> 
> Otherwise someone might use a deprecated option, but might not know why it's not good to use it, or what to use instead.
</details>
Hum...
Then maybe something like `{ deprecated: true, deprecatedMessage: 'Useful message' }` and when deprecated message is empty we output a default message.
Right now, I fear that 'This option is exposed for legacy reason, and the recommendation is to not use this option.' will be copy-pasted everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/62)*

**Comment by dms1lva** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/62#-:-KM0iD3xDX-fdOmn6v3d:1417088721)*

**Comment by olamothe** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/Facet/Facet.ts, line 131 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/62#-KM0BeGsi6UgyNqo-osm:-KM145WGU9_nNvH0Vjn1:-416267687) ([raw file](https://github.com/coveo/search-ui/blob/fe42bcd7188f1411f4fd7f7c628859b1a450196c/src/ui/Facet/Facet.ts#L131)):*
<details><summary><i>Previously, mcarpentierCoveo (Mathieu Carpentier) wrote…</i></summary>
> Hum...
> Then maybe something like `{ deprecated: true, deprecatedMessage: 'Useful message' }` and when deprecated message is empty we output a default message.
> Right now, I fear that 'This option is exposed for legacy reason, and the recommendation is to not use this option.' will be copy-pasted everywhere.
</details>
Hum, but I like the idea of "forcing" the dev to actually write a useful message instead of a canned one. 

If people just copy paste the message I think we can better shame them in the PR :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/62)*

**Pull request merged**
