### PR TITLE
dont draw slider graph when in responsive mode

### PR DESCRIPTION
**Pull request by dms1lva**
https://coveord.atlassian.net/browse/JSUI-927

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/80)

### CODE REVIEW

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/80#-:-KMQlq3KEtdTRwMMioP4:1417088721)*

**Comment by olamothe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/ui/Misc/Slider.ts, line 647 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/80#-KMUSUiFWpXKE7_hY2nn:-KMUSUiFWpXKE7_hY2no:697211968) ([raw file](https://github.com/coveo/search-ui/blob/94ef0767ef0193952bcf8f4a055e75fcf745e159/src/ui/Misc/Slider.ts#L647)):*
> ```XML
> 
>   public draw(data: ISliderGraphData[] = this.oldData) {
>     if (data && !this.root.hasClass('coveo-small-search-interface')) {
> ```

Humm, not totally certain that adding check for this everywhere will scale. If we ever change the css class, we'll need to change this everywhere.

Possible to add a public method on the `SearchInterface` ? `isSmallInterface()`maybe  ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/80)*

**Comment by olamothe** [comment]
:lgtm:

Just the small change for the css class name check.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/80#-:-KMUStRdUlkX8iOEbpuw:-1596287733)*

**Comment by dms1lva** [comment]
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/Misc/Slider.ts, line 647 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/80#-KMUSUiFWpXKE7_hY2nn:-KMV3RL2p0fW30sJScun:-152956679) ([raw file](https://github.com/coveo/search-ui/blob/94ef0767ef0193952bcf8f4a055e75fcf745e159/src/ui/Misc/Slider.ts#L647)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Humm, not totally certain that adding check for this everywhere will scale. If we ever change the css class, we'll need to change this everywhere.
> 
> Possible to add a public method on the `SearchInterface` ? `isSmallInterface()`maybe  ?
</details>
Added it. Also added setSmallInterface  and unsetSmallInterface. Would be great if you could check out the latest commit to make sure everything is ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/80)*

**Comment by olamothe** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/80#-:-KMVVkFXrgonB9UXC4H6:1417088721)*

**Pull request merged**
