### PR TITLE
Added initialChoice to ResultsPerPage component

### PR DESCRIPTION
**Pull request by francoislg**
[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/143)

### CODE REVIEW

**Comment by olamothe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/Pager/ResultsPerPage.ts, line 41 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/143#-KPOCW2wWIFfrmz93vWo:-KPOCW2wWIFfrmz93vWp:bnmsrla) ([raw file](https://github.com/coveo/search-ui/blob/7c90e92f96561dd9f6f493463fb66527ca551047/src/ui/Pager/ResultsPerPage.ts#L41)):*
> ```XML
>      * The default value is 0.
>      */
>     initialChoice: ComponentOptions.buildNumberOption({ defaultValue: 0 })
> ```

It would be better to set no default value (so the default value would actually be undefined).

If it's undefined, pick the first choice in the list.

Also, you should add defensive code against if someone set an initial choice that does not exists in the choices displayed.

I can easily imagine a setup where someone change the `choicesDisplayed` option, but forget to change the `initialChoice` accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/143)*

**Comment by francoislg** [comment]
*[src/ui/Pager/ResultsPerPage.ts, line 41 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/143#-KPOCW2wWIFfrmz93vWo:-KPOrWVMgtcSUTDk9DXW:b-6vgg2l) ([raw file](https://github.com/coveo/search-ui/blob/7c90e92f96561dd9f6f493463fb66527ca551047/src/ui/Pager/ResultsPerPage.ts#L41)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> It would be better to set no default value (so the default value would actually be undefined).
> 
> If it's undefined, pick the first choice in the list.
> 
> Also, you should add defensive code against if someone set an initial choice that does not exists in the choices displayed.
> 
> I can easily imagine a setup where someone change the `choicesDisplayed` option, but forget to change the `initialChoice` accordingly.
</details>
I agree with you on the `undefined` value instead of 0, so be it! :)

I was on the fence about the validation. I tried setting it to a value that was not in the choice while testing, and while it doesn't make sense, it also doesn't break anything. It simply sets the current results per page to the initial choice, without highlighting any of the buttons, and when you click on a new value, it works as usual.

If you would rather add a warning, I will gladly add it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/143)*

**Comment by olamothe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/Pager/ResultsPerPage.ts, line 41 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/143#-KPOCW2wWIFfrmz93vWo:-KPP07gcx1r86e0MYctV:benqc52) ([raw file](https://github.com/coveo/search-ui/blob/7c90e92f96561dd9f6f493463fb66527ca551047/src/ui/Pager/ResultsPerPage.ts#L41)):*
<details><summary><i>Previously, francoislg (Francois Lachance-Guillemette) wrote…</i></summary>
> I agree with you on the `undefined` value instead of 0, so be it! :)
> 
> I was on the fence about the validation. I tried setting it to a value that was not in the choice while testing, and while it doesn't make sense, it also doesn't break anything. It simply sets the current results per page to the initial choice, without highlighting any of the buttons, and when you click on a new value, it works as usual.
> 
> If you would rather add a warning, I will gladly add it :)
</details>
Yes, add a warning in the console when you encounter the error.

If it works already and does not break, great, but we need to make sure it's actually tested and won't break in the future.

Add some UT for this please ! :) 

Also one UT that checks that if initialChoice is undefined, we really do end up with the first choice selected.


Thank you !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/143)*

**Comment by olamothe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/ui/ResultsPerPageTest.ts, line 79 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/143#-KPPH9FhyG-qn6nTGHwb:-KPPH9FiWTqI6J2GFNra:b1sgrbh) ([raw file](https://github.com/coveo/search-ui/blob/bda5a1e2f85e05c802ba78a2528368d8e9c777a0/test/ui/ResultsPerPageTest.ts#L79)):*
> ```XML
>           results: FakeResults.createFakeResults(1000)
>         });
>         expect(test.env.queryController.options.resultsPerPage).toBe(aChoiceNotDisplayed);
> ```

Hum, okay so it select the one not displayed ? isn't that weird ? 

I was hoping it would fallback to the first `choicesDisplayed`.

Otherwise, don't we end up in a situation where the query is done with 15 results per page, but the component shows that `3` is selected ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/143)*

**Comment by francoislg** [comment]
*[test/ui/ResultsPerPageTest.ts, line 79 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/143#-KPPH9FhyG-qn6nTGHwb:-KPSSKQJN9aJHKDV7mNo:bulp4fo) ([raw file](https://github.com/coveo/search-ui/blob/bda5a1e2f85e05c802ba78a2528368d8e9c777a0/test/ui/ResultsPerPageTest.ts#L79)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Hum, okay so it select the one not displayed ? isn't that weird ? 
> 
> I was hoping it would fallback to the first `choicesDisplayed`.
> 
> Otherwise, don't we end up in a situation where the query is done with 15 results per page, but the component shows that `3` is selected ?
</details>
It results in no button highlighted and 3 results per page are shown



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/143)*

**Comment by olamothe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/ui/ResultsPerPageTest.ts, line 79 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/143#-KPPH9FhyG-qn6nTGHwb:-KPSiHi79nwPtDUzYs_Y:b48pbgm) ([raw file](https://github.com/coveo/search-ui/blob/bda5a1e2f85e05c802ba78a2528368d8e9c777a0/test/ui/ResultsPerPageTest.ts#L79)):*
<details><summary><i>Previously, francoislg (Francois Lachance-Guillemette) wrote…</i></summary>
> It results in no button highlighted and 3 results per page are shown
> 
> 
</details>
Ok, normally in other instance similar to this in the framework (for example, someone specifying a `Tab` that does not exist in the interface in the url with #t=doesNotExist), it fallback on the first one.

In this case, it should behave similarly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/143)*

**Comment by francoislg** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[test/ui/ResultsPerPageTest.ts, line 79 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/143#-KPPH9FhyG-qn6nTGHwb:-KPSkI1hY7R3CNaFnWug:b3xngn4) ([raw file](https://github.com/coveo/search-ui/blob/bda5a1e2f85e05c802ba78a2528368d8e9c777a0/test/ui/ResultsPerPageTest.ts#L79)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Ok, normally in other instance similar to this in the framework (for example, someone specifying a `Tab` that does not exist in the interface in the url with #t=doesNotExist), it fallback on the first one.
> 
> In this case, it should behave similarly.
</details>
Already done :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/143)*

**Pull request merged**
