### PR TITLE
ResponsiveFacets - Fix cropped facet search results

### PR DESCRIPTION
**Pull request by dms1lva**
Re-implement the way pop-ups are placed. Use PopUpUtils to place the facet search results dropdown.

https://coveord.atlassian.net/browse/JSUI-945

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/101)

### CODE REVIEW

**Comment by olamothe** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/ui/Facet/FacetSearch.ts, line 25 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8cwcKeoQz71Zib9P8:-KN8cwcKeoQz71Zib9P9:-824785438) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/ui/Facet/FacetSearch.ts#L25)):*
> ```XML
> import {IFacetSearchValuesListKlass} from './FacetSearchValuesList';
> import {FacetValueElement} from './FacetValueElement';
> import _ = require('underscore');
> ```

Won't be needed anymore once .Dependencies is made obsolete (Webpack will provide _ to all module automatically)

---

*[src/ui/Facet/FacetSearch.ts, line 113 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8dEFtg-6EmMl2pbIN:-KN8dEFtg-6EmMl2pbIO:2097897961) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/ui/Facet/FacetSearch.ts#L113)):*
> ```XML
>    */
>   public completelyDismissSearch() {
>     console.log('dismiss');
> ```

Remove

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 194 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8dULySd3BiVNmnJ-2:-KN8dULySd3BiVNmnJ-3:2026657038) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L194)):*
> ```XML
>   private dismissFacetSearches() {
>     _.each(this.facets, facet => {
>       if (facet.facetSearch.currentlyDisplayedResults) {
> ```

`facetSearch` might not exists if the facet has nothing to search. Code defensively around it.

---

*[src/utils/PopupUtils.ts, line 180 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8doIQIn7Ln_pgWsAG:-KN8doIQIn7Ln_pgWsAH:613371187) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/utils/PopupUtils.ts#L180)):*
> ```XML
> 
>   // based on http://api.jquery.com/offset/
>   private static getOffset(el: HTMLElement) {
> ```

Shouldn't these method be public in the `Dom` class ?

They could be useful in another context, not only for Popup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101)*

**Comment by Dominionized** [comment]
Reviewed 11 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101)*

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Reviewed 11 of 12 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101#-:-KN95E8-VBQ_tmLPpQaj:1417088721)*

**Comment by dms1lva** [comment]
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ui/Facet/FacetSearch.ts, line 113 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8dEFtg-6EmMl2pbIN:-KN8hAcu4j9GVWSmLoBH:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/ui/Facet/FacetSearch.ts#L113)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Remove
</details>
Done.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 194 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8dULySd3BiVNmnJ-2:-KN8hDuaer-uH9wJLQD5:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L194)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> `facetSearch` might not exists if the facet has nothing to search. Code defensively around it.
</details>
Done.

---

*[src/utils/PopupUtils.ts, line 180 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8doIQIn7Ln_pgWsAG:-KN96fjNK1O1gZBMNfzm:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/utils/PopupUtils.ts#L180)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Shouldn't these method be public in the `Dom` class ?
> 
> They could be useful in another context, not only for Popup
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101)*

**Comment by dms1lva** [comment]
Review status: 9 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/ui/Facet/FacetSearch.ts, line 25 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KN8cwcKeoQz71Zib9P8:-KN97lL4SmdqjEhEDZzy:-1401608966) ([raw file](https://github.com/coveo/search-ui/blob/8ea662dc7f99c509843d8bf85eccd0135169353a/src/ui/Facet/FacetSearch.ts#L25)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Won't be needed anymore once .Dependencies is made obsolete (Webpack will provide _ to all module automatically)
</details>
Alright when your PR is merged i'll modify my stuff accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101)*

**Comment by Dominionized** [comment]
Reviewed 2 of 4 files at r3, 2 of 3 files at r4.
Review status: 11 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 129 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/101#-KND9SQwDQLRZuvGDi5B:-KND9SQwDQLRZuvGDi5C:-490633221) ([raw file](https://github.com/coveo/search-ui/blob/b711a4325afbca7f917c2f9b2cb46673e605125c/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L129)):*
> ```XML
> 
>   private bindDropdownContentEvents() {
>     this.onDocumentClick = event => {
> ```

I changed the behaviour of this in JSUI-953 (no more event listener on the whole document) so we'll have integrate when merging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101)*

**Comment by Dominionized** [comment]
Reviewed 1 of 4 files at r3, 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101)*

**Comment by olamothe** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101#-:-KNDnVkBzGxOMcTT26vB:1417088721)*

**Comment by olamothe** [comment]
Reviewed 1 of 2 files at r2, 3 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/101)*

**Pull request merged**
