### PR TITLE
JSUI-692 - SonarQube integration + some other stuff

### PR DESCRIPTION
**Pull request by Dominionized**
This is an early pull request.

What it does :

* **Generates an lcov code coverage report**
  1. Karma takes the ES5 code, runs the tests and generates coverage for ES5 in an Istanbul (JSON) format.
  2. remap-istanbul takes the coverage and processes it with the source maps that Webpack generated, removing at the same time the dependencies (Underscore, d3, etc.) from the coverage report. It allows for a more accurate report. This also outputs in Istanbul (JSON) format.
  3. istanbul-combine takes the Istanbul code coverage and converts it to the lcov format, because Sonar only supports that. Also generates an HTML report (**very** useful) in the `coverage/lcov-report` directory.
* **Pushes to Sonar.** Pushes to Sonar (sonar.cloud.coveo.com) the lcov coverage as well as TypeScript source files. This is used by Sonar to generate metrics.

Current problems :

* Sonar doesn't support TypeScript by default. I asked DevBooster to install [this plugin](https://github.com/Pablissimo/SonarTsPlugin) for me but it hasn't been done yet. If the plugin turns out to be unstable or not worth using, we might have to rely on pushing the ES5 code and code coverage directly (which is far from optimal, because it is generated from tsc).
* sonar.cloud.coveo.com doesn't seem to be available from the outside. Travis is not able to push the coverage and source code to the MySQL database.

By the way, this PR enables source maps for development too.

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/37)

### CODE REVIEW

**Comment by Dominionized** [comment]
We might have to do some changes. As it turns out, making sonar.cloud.coveo.com accessible to the Internet might not be the best solution. The proposed solution is to create an internal Jenkins task which fetches the repo periodically, generates the code coverage and pushes it to Sonar.

**Comment by wfortin** [comment]
Instead of pushing the metrics to sonar with a Jenkins task, you might want to try instead : 
* [Codeclimate](https://codeclimate.com/) with https://github.com/tkqubo/codeclimate-tslint
* [BitHound](https://www.bithound.io/features) which support TypeScript ootb

And maybe combine with [coveralls](https://coveralls.io/) for the code coverage.

Looks like the combination of bithound with coveralls is the best fit for you guys. And it's free for open source 🎉

**Comment by Dominionized** [comment]
What do you think about that @olamothe ? Should I keep working on integrating with SonarQube or try something else ?

**Comment by Dominionized** [comment]
I have made some changes today. Currently :

- The proper code coverage is generated according to sourcemaps and displayed in the terminal when running `npm test`.
- Pushing to Sonar somewhat works when the machine has access to sonar.cloud.coveo.com, although, for some reason, the coverage is not displayed in its web interface.

We might want to reconsider using Sonar in favour of something else, but in the meantime, the code coverage calculation is integrated into the build process.

**Comment by Dominionized** [comment]
The HTML coverage report is available under `bin/coverage/lcov-report`.

Would be ready to merge

**Comment by dms1lva** [comment]
:lgtm:

---

Reviewed 22 of 45 files at r1, 18 of 21 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/37#-:-KN81BeLa8DHaiUZjTO3:1417088721)*

**Comment by olamothe** [comment]
:lgtm:

---

Reviewed 12 of 45 files at r1, 13 of 21 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 26 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8XgVCAWxeFNumzox1:-KN8XgVDeU47PQULC7n9:1328173216) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/.travis.yml#L26)):*
> ```YAML
>   - COMMIT_AUTHOR_EMAIL: sandbox_JSUI@coveo.com
>   - secure: CEJ4E2GzA31nJc1T4YdcFuG/1ivaMVbmhc+yFg0f4yGzmiy+VCZn673mhysB7zEOTIfxSyz7ZozkNyKaWFUKwzayNoMI2XfGedtfjtniXYX2+VXDf2zwnPtZB5YnAmR1oTqGKtrXj8ietyz6nd5oUYIIF1RkCpFG9ycMqb6YDT2U8ukt+IxpQO+uJyj1vD82CkW4YAydmUPaeGRSzjXDbi5aGNo63gykv74SBskhISHw/PThQLC1TPyRVnbWKdv24ddykR+BK5ZvwQO23x6APZfGzqd2HKpU2cwK+XULHYgIlkNsjPhys6UpY35TcT+h5/OQBTFXXOFucbgOy2SLsjePe7O+9icbb7T4V63mURXCzxuJviDRpjdw2XlCjT5Oj039ClViGzxlW3q9mO4UreeN4975LzJXPId8dSGYJ46KWUZ9e7SIMxBib26ADDom0oJomiENuHp0rYRAYj6TxDilMw8/OK4FL6VwxK27I8fJ6bw0ADSgU57nuzX1rkPWLNGv5mZlZboHWwI/Bq5tqJXjZEc7m2rO9YUmlFjX+YeNkXSokT0I6KxBTU3mRkXQpHO4nP47bUDWQRiAeeoRhsiQnbdCUBkhSLX0QEJbpBJwx2ZlNYDAweiB3fN7nfxhAwEnVtco4U1UBHci9c+hfOxjDjSav0GXeX+hMM8w56U=
>   - secure: q/ewpGNJZGO1IuOTh/+UP6Dc02f7qaXpMUweWTCm+R/MQi7uxhegBpw5GtYbqgC9RU22NXIr1r1Zqeam++iNGawDVoX4RPiRaz9y5ZW8I5ZTk48jA6VhJ0sD5VRbRS8i4MYfqi2qi+SZTRCkI23eedWLyNtQe2SsiWNsfD4wKfJItVp2v3R7LyJtIiZNgCjRTHIDIkYBvhqMejbaE2/+wqnw+jy4KRcJ4N3lJJpShUXv7OVZhVktCnbMA2rxOK/rVqGA09wbdx66NdegF/my7M1562BGs3EZ1bqX1N9jVOqNYOsXI0x6TVcQOTTQX9YmvNBHdU+NaMX1dxog/mqTzrPKNdsYdDIewyehLb4dcC2+QCpGIB0KEEAjVvyHiTL0bfJq5LllJ3QKCGpKHd+AZ84grddmaGZHGm2Caz3g0hqK68gsN0RIoDePl5aUXOu2fvRx4UVlwV6TcesxTSqRD4Cskyb9A544a5dxnSCI0neUEMh6oTG/7WtfyQ7xekjhjI7OG8rEeH+izCgTog5CxlnnpOap+srZqPBrL1mwGz4As3Gvub4kCxr6hGKlgy4MRCzokJXiQSt1iLgCLWb27Gyt1ETSz93lIaIzZs8y+2wFmycbW/7xu6XrD70JRqV5BxZjedcY3NbgTvOLGVod7ga3mY5spl4VpNCYMsa/Iws=
> ```

What's that ?
Add a comment in the travis file to explain what it's used for.

---

*[package.json, line 73 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8Xwa0b2Y0oQbf8xiN:-KN8Xwa0b2Y0oQbf8xiO:2100877117) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/package.json#L73)):*
> ```JSON
>     "gulp-sass": "2.0.4",
>     "gulp-shell": "^0.5.2",
>     "gulp-sonar": "^2.1.0",
> ```

Is this still needed ?

---

*[tsconfig.json, line 8 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8Y0QSa8FsQRnc8Gtv:-KN8Y0QSa8FsQRnc8Gtw:358267752) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/tsconfig.json#L8)):*
> ```JSON
>     "experimentalDecorators": true,
>     "outDir": "./bin",
>     "sourceMap": true
> ```

Does this conflict with the webpack sourcemap configuration ?

---

*[webpack.config.js, line 49 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8Y6Q0xpG6JA9DGRtY:-KN8Y6Q0xpG6JA9DGRtZ:1748672565) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/webpack.config.js#L49)):*
> ```JavaScript
>         loader: 'string-replace-loader',
>         query: {
>           search: '//# sourceMappingURL=underscore-min.map',
> ```

Add a comment in the configuration that explains why we need to do this.

---

*[gulpTasks/test.js, line 9 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8YrfBXdU9jWzY1Bna:-KN8YrfCZ22nfIR_vyrP:114301927) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/gulpTasks/test.js#L9)):*
> ```JavaScript
> const remapIstanbul = require('remap-istanbul/lib/gulpRemapIstanbul');
> 
> const COVERAGE_DIR = 'bin/coverage';
> ```

Use `path.resolve('bin/coverage')` , this prevents some nasty/hard to find bugs on various OS.

---

*[src/controllers/QueryController.ts, line 18 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8Z68QKAbSb7CGxmg-:-KN8Z68QKAbSb7CGxmg0:1789991759) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/src/controllers/QueryController.ts#L18)):*
> ```XML
> import {Promise} from 'es6-promise';
> import {BaseComponent} from '../ui/Base/BaseComponent';
> import * as _ from 'underscore';
> ```

Won't be needed anymore soon, _ will be provided to all module automatically with webpack

---

*[src/misc/Assert.ts, line 3 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8ZJjEY52qFAP7nBKw:-KN8ZJjEY52qFAP7nBKx:-485711229) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/src/misc/Assert.ts#L3)):*
> ```XML
> import {Logger} from '../misc/Logger';
> import {Utils} from '../utils/Utils';
> import * as _ from 'underscore';
> ```

Same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/37#-:-KN8ZjHKRwN9cJjLSLwx:1417088721)*

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Reviewed 3 of 45 files at r1, 4 of 21 files at r2, 2 of 2 files at r3, 1 of 3 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/37#-:-KN8ygn0xQYnPQruCw8U:1417088721)*

**Comment by Dominionized** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 26 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8XgVCAWxeFNumzox1:-KNCgcwVjpiJX7EUgXrH:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/.travis.yml#L26)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> What's that ?
> Add a comment in the travis file to explain what it's used for.
</details>
Done.

---

*[package.json, line 73 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8Xwa0b2Y0oQbf8xiN:-KNCgn8fyvPRxrU29Jgx:160394146) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/package.json#L73)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Is this still needed ?
</details>
Yes

---

*[tsconfig.json, line 8 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/37#-KN8Y0QSa8FsQRnc8Gtv:-KNChBlQswWPrm82mxuL:1123104058) ([raw file](https://github.com/coveo/search-ui/blob/7df69448e91f4f288a60aa0faf58279cb1b1ebe4/tsconfig.json#L8)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Does this conflict with the webpack sourcemap configuration ?
</details>
No. It's actually needed for webpack sourcemaps to work properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/37)*

**Pull request merged**
