### PR TITLE
commit message hook - add jira issue number from branch name

### PR DESCRIPTION
**Pull request by dms1lva**
https://coveord.atlassian.net/browse/JSUI-888

[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/112)

### CODE REVIEW

**Comment by Dominionized** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/112)*

**Comment by Dominionized** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/112#-:-KNgZZOz1ZkyPQDL2uc6:1417088721)*

**Comment by olamothe** [comment]
:lgtm:

Good stuff.

I'm guessing in the future we could also have a hook to help generate changelogs ?

There is a lot of tool that do this, but the commit message need to follow a strict guideline. (eg : https://github.com/lob/generate-changelog) 

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/112#-:-KNhO7s7rqloFsBEp5Ze:-50172280)*

**Comment by dms1lva** [comment]
Ya we could definitely have a hook that denies any commit that does not fit a specific format.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/112#-:-KNhRYpgaWBYVERyWjj8:1555581867)*

**Pull request merged**
