### PR TITLE
Jsui 892

### PR DESCRIPTION
**Pull request by mcarpentierCoveo**
[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/128)

### CODE REVIEW

**Comment by Dominionized** [comment]
Reviewed 13 of 57 files at r1, 2 of 5 files at r3.
Review status: 15 of 57 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[webpack.common.config.js, line 30 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp-gYj3CdrVSMvFY3J:-KOp-gYj3CdrVSMvFY3K:bq2dmi6) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/webpack.common.config.js#L30)):*
> ```JavaScript
>     }
>   },
>   devtool: 'inline-source-map',
> ```

Does this line change still work with the Chrome DevTools ? I had changed it a while back from `inline-source-map` to `source-map`.

---

*[sass/_AdvancedSearch.scss, line 27 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp08G2p4UCAQK8hWbC:-KOp08G2p4UCAQK8hWbD:bdk32cd) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/sass/_AdvancedSearch.scss#L27)):*
> ```SCSS
> 
> .coveo-advanced-search-date-input-section {
>   display: flex;
> ```

Just in case, you should probably use the Bourbon mixins for flex. It adds all of the vendor prefixes for older browsers.

We should probably try to use autoprefixer instead but for now, it's all we got.

---

*[sass/_AdvancedSearch.scss, line 90 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp1NfS2o5obyZ9RKBe:-KOp1NfS2o5obyZ9RKBf:b45dtqg) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/sass/_AdvancedSearch.scss#L90)):*
> ```SCSS
> 
> #coveo-advanced-search-select-day {
>   width:50px
> ```

Spaces plz :stuck_out_tongue: 

---

*[src/ui/AdvancedSearch/AdvancedSearch.ts, line 42 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp1oL4DaxCC3KjHr3G:-KOp1oL4DaxCC3KjHr3H:b2etma7) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/src/ui/AdvancedSearch/AdvancedSearch.ts#L42)):*
> ```XML
>     /**
>      * Specifies whether or not to include the built-in keywords section.
>      * Default is true
> ```

Just for the sake of Markdown-fu, you can put `true` (all code values, actually) in backticks, it will display better in TypeDoc

---

*[src/ui/AdvancedSearch/AdvancedSearch.ts, line 93 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp2C2lcBpX5MBpIq0z:-KOp2C2lcBpX5MBpIq1-:b-wbtg9h) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/src/ui/AdvancedSearch/AdvancedSearch.ts#L93)):*
> ```XML
>   private buildCloseButton() {
>     var closeButton = $$('div', { className: 'coveo-advanced-search-panel-close' }, $$('span', { className: 'coveo-icon' }).el)
>     closeButton.on('click', () => {
> ```

It's a matter of personal preference and code style, but personally, I like to put the anonymous function inline (without brackets) when it contains only 1 line. I find it cleaner.

Ex : 
`closeButton.on('click', () => this.close());`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128)*

**Comment by mcarpentierCoveo** [comment]
Review status: 15 of 57 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[webpack.common.config.js, line 30 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp-gYj3CdrVSMvFY3J:-KOv3VOtRwXXePjkIUSL:b-csa661) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/webpack.common.config.js#L30)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Does this line change still work with the Chrome DevTools ? I had changed it a while back from `inline-source-map` to `source-map`.
</details>
Yes it works.
Not sure why, but after importing pikaday, when using `source-map` the file name mapping was all wrong.

---

*[sass/_AdvancedSearch.scss, line 27 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp08G2p4UCAQK8hWbC:-KOv4fBUATgVT8vXaW7o:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/sass/_AdvancedSearch.scss#L27)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Just in case, you should probably use the Bourbon mixins for flex. It adds all of the vendor prefixes for older browsers.
> 
> We should probably try to use autoprefixer instead but for now, it's all we got.
</details>
Done.

---

*[sass/_AdvancedSearch.scss, line 90 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp1NfS2o5obyZ9RKBe:-KOv4fwQaUOFvRaSb4jC:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/sass/_AdvancedSearch.scss#L90)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Spaces plz :stuck_out_tongue: 
</details>
Done.

---

*[src/ui/AdvancedSearch/AdvancedSearch.ts, line 42 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp1oL4DaxCC3KjHr3G:-KOv4npDLLkKcAwCkr8y:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/src/ui/AdvancedSearch/AdvancedSearch.ts#L42)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Just for the sake of Markdown-fu, you can put `true` (all code values, actually) in backticks, it will display better in TypeDoc
</details>
Done.

---

*[src/ui/AdvancedSearch/AdvancedSearch.ts, line 93 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp2C2lcBpX5MBpIq0z:-KOv4zA9xN-FrjXwSKIW:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/src/ui/AdvancedSearch/AdvancedSearch.ts#L93)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> It's a matter of personal preference and code style, but personally, I like to put the anonymous function inline (without brackets) when it contains only 1 line. I find it cleaner.
> 
> Ex : 
> `closeButton.on('click', () => this.close());`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128)*

**Comment by dms1lva** [comment]
:lgtm:

---

Reviewed 21 of 57 files at r1, 1 of 1 files at r2, 2 of 5 files at r3, 2 of 2 files at r4.
Review status: 29 of 57 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128#-:-KOzpmX8MOmtYXggVMfJ:bnfp4nl)*

**Comment by olamothe** [comment]
:lgtm:

Good stuff.

Couple of important point : Scan for all reference the the `document` reserved keyword, and replace those.

I would like more UT for the API that allow external code to push new content in the advanced search component.

We will also need new documentation about the way external code can push content in the advanced search component on developers.coveo.com, plus how it can be added to the search page (the markup you need, etc.)

Because we probably won't be adding this component OOTB in all search page.

---

Reviewed 51 of 57 files at r1, 1 of 1 files at r2, 3 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[webpack.common.config.js, line 30 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp-gYj3CdrVSMvFY3J:-KPDZmfn-ej8E_U7vLMk:b-mxjqb) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/webpack.common.config.js#L30)):*
<details><summary><i>Previously, mcarpentierCoveo (Mathieu Carpentier) wrote…</i></summary>
> Yes it works.
> Not sure why, but after importing pikaday, when using `source-map` the file name mapping was all wrong.
</details>
Does the UT reporting works correctly as well ?

I would also prefer if we could make it work with a separate source map file instead of all inline.

---

*[src/ExternalModulesShim.ts, line 5 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDaccLESI_i91wajIQ:-KPDaccLESI_i91wajIR:bbocn5n) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ExternalModulesShim.ts#L5)):*
> ```XML
> export const MagicBox = require('exports?Coveo.MagicBox!../node_modules/coveomagicbox/bin/MagicBox.min.js');
> export const LocaleString = require('exports?window.String.toLocaleString!../lib/l10n.min.js');
> export const Pikaday = require('pikaday');
> ```

It's a bit weird to put Pikaday here since we do not need to shim it, it already export correctly to common js if I understand.

The other modules in this file are special since they are "shimmed" with webpack to exports their global variable.

This is not the case for Pikaday.

---

*[src/Index.ts, line 96 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDaxMz8c0jE2ehi4nO:-KPDaxN-Q_n4zezRgp0m:bat0b69) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/Index.ts#L96)):*
> ```XML
> export {jQueryInstance as $} from './ui/Base/CoveoJQuery';
> export {underscoreInstance as _} from './ui/Base/CoveoUnderscore';
> export {AdvancedSearch} from './ui/AdvancedSearch/AdvancedSearch';
> ```

Hum do we really need to export all those classes in the global scope ?

I think only exporting the top level component (AdvancedSearch) would be enough.

---

*[src/events/AdvancedSearchEvents.ts, line 8 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDezs4iZfNEbeuO-TX:-KPDezs4iZfNEbeuO-TY:b-bxeayh) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/events/AdvancedSearchEvents.ts#L8)):*
> buildingAdvancedSearc

---

*[src/ui/AdvancedSearch/DateInput/DateInput.ts, line 55 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDbWkEvjo6Ev6H1yZj:-KPDbWkEvjo6Ev6H1yZk:begjtbt) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DateInput/DateInput.ts#L55)):*
> ```XML
>   }
> 
>   private desactivateAllInputs() {
> ```

deactivate

---

*[src/ui/AdvancedSearch/DocumentInput/AdvancedFieldInput.ts, line 17 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDbpsU06Y8cdzECUTT:-KPDbpsU06Y8cdzECUTU:bsdqu7e) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DocumentInput/AdvancedFieldInput.ts#L17)):*
> ```XML
> 
>   public build(): HTMLElement {
>     let document = $$(super.build());
> ```

Hum using the reserved keyword document is not a good idea / best practice.

---

*[src/ui/AdvancedSearch/DocumentInput/DocumentInput.ts, line 12 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDc0zWQDp55c3Rd4ZC:-KPDc0zWQDp55c3Rd4ZD:b-god7g2) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DocumentInput/DocumentInput.ts#L12)):*
> ```XML
> 
>   public build(): HTMLElement {
>     let document = $$('div', { className: 'coveo-advanced-search-document-input-section' });
> ```

Do not use the reserved keyword document as a variable

---

*[src/ui/AdvancedSearch/DocumentInput/SimpleFieldInput.ts, line 18 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDc6BIVvWL8Mh8fqbF:-KPDc6BIVvWL8Mh8fqbG:blnv3rl) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DocumentInput/SimpleFieldInput.ts#L18)):*
> ```XML
> 
>   public build(): HTMLElement {
>     let document = $$(super.build());
> ```

Document reserved keyword

---

*[src/ui/AdvancedSearch/Form/NumericSpinner.ts, line 17 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDcUqgRQNjClMGQ5Dc:-KPDcUqgRQNjClMGQ5Dd:b-1dcweu) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/Form/NumericSpinner.ts#L17)):*
> ```XML
> 
>   public getIntValue(): number {
>     return this.getSpinnerInput().value ? parseInt(this.getSpinnerInput().value) : this.min;
> ```

When you use parseInt, always pass the second parameter `10` to the function (with is the the base you wish to parse it.)

Otherwise if someone enters `08` in the input, it will try to parse it in octal. oO

---

*[strings/strings.json, line 5090 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDdsTaKPJLiMjC8wwg:-KPDdsTb25aaqZGICjeH:b-br93r4) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/strings/strings.json#L5090)):*
> ```JSON
>     "fr": "Aucun de ces mots"
>   },
>   "AdvancedSearchDateSectionTitle": {
> ```

The keyword `Date` is already translated, use this instead.
Check for all other words to double check that there is no duplication.

Also, the rest of the localized string use the actual word as a key, not the place or component where it is used. 

So for example, `AdvancedSearchAnytimeLabel` should become simply `Anytime`

---

*[test/Test.ts, line 34 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDeLLf1aZohJZPUXvE:-KPDeLLf1aZohJZPUXvF:b-yjhi7a) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/test/Test.ts#L34)):*
> ```XML
> import {ModelTest} from './models/ModelTest';
> ModelTest();
> /// <reference path="ui/AdvancedSearch/AdvancedSearchTest.ts" />
> ```

The tests should work like the other one and use common js modules instead of /// references

---

*[test/ui/AdvancedSearch/AdvancedSearchTest.ts, line 1 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDeXh0JRJiXzgPnley:-KPDeXh0JRJiXzgPnlez:b-5cvqu4) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/test/ui/AdvancedSearch/AdvancedSearchTest.ts#L1)):*
> ```XML
> /// <reference path="../../Test.ts" />
> ```

Same comment as `Test.ts` all the tests should use common js to export their tests, instead of /// references

---

*[test/ui/AdvancedSearch/AdvancedSearchTest.ts, line 4 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDeisegXaJi64yRjJE:-KPDeisegXaJi64yRjJF:b-s09uuy) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/test/ui/AdvancedSearch/AdvancedSearchTest.ts#L4)):*
> ```XML
> 
> module Coveo {
>   describe('AdvancedSearch', () => {
> ```

We should add tests for the API of the extension point.

Check that the correct events are triggered `buildingAdvancedSearch` and that external code can push content and that it is rendered + executed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128#-:-KPDh7D2L3M4-dgxhuqe:b-vpl5di)*

**Comment by Dominionized** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128)*

**Comment by olamothe** [comment]
The code looks okay, but the extension point remains to be worked on.

External code needs to be able to include a generic numeric spinner/input text/datepicker/radio button etc with all our styling effortlessly, not a premade input like document_size for example.



We'll leave this in a PR for now, and make the adjustment later. We should not merge this immediately.

With pseudo code, the extension point should look something like this : 

    search.addEventListener('buildingAdvancedSearch', function(data) {
        data.push({
            title : 'Foobar'
            type : Coveo.AdvancedSearch.NUMERIC_SPINNER,
            onChange : function(spinner) {
                spinner.get();
                spinner.set();
            },
            modifyQuery: function(queryBuilder, spinner) {
                queryBuilder.expression.add(spinner.get())
             }
        })
    })
    

---

Reviewed 43 of 45 files at r6.
Review status: 54 of 56 files reviewed at latest revision, 19 unresolved discussions.

---

*[tsconfig.json, line 112 \[r6\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPYC-wWnJou9_UvFXqz:-KPYC-wWnJou9_UvFXr-:b-y81yc5) ([raw file](https://github.com/coveo/search-ui/blob/7ca6d5df47beffd24d63d19b40fcf54fd7bd5da3/tsconfig.json#L112)):*
> ```JSON
>     "src/strings/DefaultLanguage.ts",
>     "src/strings/Strings.ts",
>         "src/ui/AdvancedSearch/AdvancedSearch.ts",
> ```

Hum, alignment is weird.

---

*[src/ui/AdvancedSearch/Form/TextInput.ts, line 32 \[r6\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPYDreuJpmcgpskyaxn:-KPYDreuJpmcgpskyaxo:bnbslj2) ([raw file](https://github.com/coveo/search-ui/blob/7ca6d5df47beffd24d63d19b40fcf54fd7bd5da3/src/ui/AdvancedSearch/Form/TextInput.ts#L32)):*
> ```XML
>     let input = $$('input', { type: 'text' });
>     input.on(['keydown', 'blur'], (e: Event) => {
>       if (e instanceof KeyboardEvent && e.keyCode == 13 || e.type == 'blur') {
> ```

Could have used the KeyboardUtils module here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128#-:-KPYEoUdSH7kvFrKY3_6:bl8ix8s)*

**Comment by olamothe** [comment]
Reviewed 2 of 45 files at r6.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128)*

**Comment by mcarpentierCoveo** [comment]
I agree, but instead of using only a single type, I would specify a list of 'input types' to be able to use combinations. Then we could pass that list to `onChange` and `modifyQuery`.

---

Review status: 54 of 57 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[tsconfig.json, line 112 \[r6\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPYC-wWnJou9_UvFXqz:-KPYKq1Q8ZUSCnG1imJb:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/7ca6d5df47beffd24d63d19b40fcf54fd7bd5da3/tsconfig.json#L112)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Hum, alignment is weird.
</details>
Done.

---

*[src/Index.ts, line 96 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDaxMz8c0jE2ehi4nO:-KPYJwKuiuWr77zocUOU:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/Index.ts#L96)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Hum do we really need to export all those classes in the global scope ?
> 
> I think only exporting the top level component (AdvancedSearch) would be enough.
</details>
Done.

---

*[src/ui/AdvancedSearch/DateInput/DateInput.ts, line 55 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDbWkEvjo6Ev6H1yZj:-KPYJnbsPr56cxobRVg9:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DateInput/DateInput.ts#L55)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> deactivate
</details>
Done.

---

*[src/ui/AdvancedSearch/DocumentInput/AdvancedFieldInput.ts, line 17 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDbpsU06Y8cdzECUTT:-KPYKnM3iz0X_I_NIDtz:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DocumentInput/AdvancedFieldInput.ts#L17)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Hum using the reserved keyword document is not a good idea / best practice.
</details>
Done.

---

*[src/ui/AdvancedSearch/DocumentInput/DocumentInput.ts, line 12 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDc0zWQDp55c3Rd4ZC:-KPYJyMjId_TCJ6Klyub:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DocumentInput/DocumentInput.ts#L12)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Do not use the reserved keyword document as a variable
</details>
Done.

---

*[src/ui/AdvancedSearch/DocumentInput/SimpleFieldInput.ts, line 18 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDc6BIVvWL8Mh8fqbF:-KPYJyy31LozB3vCNH0Z:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/DocumentInput/SimpleFieldInput.ts#L18)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Document reserved keyword
</details>
Done.

---

*[src/ui/AdvancedSearch/Form/NumericSpinner.ts, line 17 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDcUqgRQNjClMGQ5Dc:-KPYJzfYTkPtGAS5WUZg:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ui/AdvancedSearch/Form/NumericSpinner.ts#L17)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> When you use parseInt, always pass the second parameter `10` to the function (with is the the base you wish to parse it.)
> 
> Otherwise if someone enters `08` in the input, it will try to parse it in octal. oO
</details>
Done.

---

*[src/ui/AdvancedSearch/Form/TextInput.ts, line 32 \[r6\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPYDreuJpmcgpskyaxn:-KPYKb39yFElo1nPaALs:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/7ca6d5df47beffd24d63d19b40fcf54fd7bd5da3/src/ui/AdvancedSearch/Form/TextInput.ts#L32)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Could have used the KeyboardUtils module here.
</details>
Done.

---

*[strings/strings.json, line 5090 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDdsTaKPJLiMjC8wwg:-KPYKcaip7NnpCgthbxY:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/strings/strings.json#L5090)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> The keyword `Date` is already translated, use this instead.
> Check for all other words to double check that there is no duplication.
> 
> Also, the rest of the localized string use the actual word as a key, not the place or component where it is used. 
> 
> So for example, `AdvancedSearchAnytimeLabel` should become simply `Anytime`
</details>
Done.

---

*[test/Test.ts, line 34 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDeLLf1aZohJZPUXvE:-KPYKeeRcjxpfud8Dg_h:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/test/Test.ts#L34)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> The tests should work like the other one and use common js modules instead of /// references
</details>
Done.

---

*[test/ui/AdvancedSearch/AdvancedSearchTest.ts, line 4 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDeisegXaJi64yRjJE:-KPYKgPYdKIZ-MLhgK99:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/test/ui/AdvancedSearch/AdvancedSearchTest.ts#L4)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> We should add tests for the API of the extension point.
> 
> Check that the correct events are triggered `buildingAdvancedSearch` and that external code can push content and that it is rendered + executed.
</details>
Done.

---

*[webpack.common.config.js, line 30 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KOp-gYj3CdrVSMvFY3J:-KPYKhzk8a2ACrDSDWqp:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/eea9a38ab40c44c88f134b7d1339e7091a726a1b/webpack.common.config.js#L30)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Does the UT reporting works correctly as well ?
> 
> I would also prefer if we could make it work with a separate source map file instead of all inline.
</details>
Done.

---

*[src/ExternalModulesShim.ts, line 5 \[r4\]](https://reviewable.io:443/reviews/coveo/search-ui/128#-KPDaccLESI_i91wajIQ:-KPYKj1byvM6Sww0s24d:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/0ed20744be6c7b8d37a9f631b3a8d0c9bcc86fe1/src/ExternalModulesShim.ts#L5)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> It's a bit weird to put Pikaday here since we do not need to shim it, it already export correctly to common js if I understand.
> 
> The other modules in this file are special since they are "shimmed" with webpack to exports their global variable.
> 
> This is not the case for Pikaday.
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128#-:-KPYHIJDhCSWjhiRz_xr:bkiwxpc)*

**Comment by dms1lva** [comment]
Reviewed 1 of 57 files at r1, 11 of 47 files at r8.
Review status: 24 of 59 files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/128)*

**Pull request merged**
