### PR TITLE
JSUI-875

### PR DESCRIPTION
**Pull request by olamothe**
https://coveord.atlassian.net/browse/JSUI-875

This adds a way to specify, in `./environments/conf.js` an array of other repositories.

When the dev server is started in the search ui repo, if this file is populated, it will create a symlink between all those other projects (in the `node_modules` folder) and the main repo.

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/43)

### CODE REVIEW

**Comment by mcarpentierCoveo** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[environments/link.externally.js, line 5 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/43#-KLIhTBf6BKkuJa0YvgJ:-KLIhTBglw7M5HUIVOaj:1625115967) ([raw file](https://github.com/coveo/search-ui/blob/15a29f82ee2be4f02e4538b6579117d247dc3559/environments/link.externally.js#L5)):*
> ```JavaScript
> /**
>  * Use this script to link the bin folder from this repository to all your external project's node_modules.
>  * This mean that
> ```

What does it mean? :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/43)*

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/43#-:-KLIi6iyKHa-0qeuDeZm:1417088721)*

**Comment by dms1lva** [comment]
Reviewed 4 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/43)*

**Comment by dms1lva** [comment]
Reviewed 3 of 8 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/43)*

**Comment by dms1lva** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/43#-:-KLM4vVhj4nDDVVgmrA_:1417088721)*

**Pull request merged**
