### PR TITLE
Swap library target variable

### PR DESCRIPTION
**Pull request by olamothe**
https://coveord.atlassian.net/browse/JSUI-895

This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/74)

### CODE REVIEW

**Comment by dms1lva** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Index.ts, line 197 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/74#-KMAA2ZCayljUUwF19Z5:-KMAA2ZCayljUUwF19Z6:-1364545682) ([raw file](https://github.com/coveo/search-ui/blob/969cd488e706fdfe0552ce44c5802a538dfd61c0/src/Index.ts#L197)):*
> ```XML
>     window['Coveo'] = this;
>   } else {
>     Object.keys(this).forEach((k) => {
> ```

Could probably use _.extend here http://underscorejs.org/#extend

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/74)*

**Comment by dms1lva** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/74#-:-KMAXsCzCotaQl7aZ1Fk:980077401)*

**Comment by dms1lva** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/74)*

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/74#-:-KMB4Bwqq-v3C4qYRHsX:1417088721)*

**Comment by olamothe** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Index.ts, line 197 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/74#-KMAA2ZCayljUUwF19Z5:-KMPEZ46z-PwTZzTybph:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/969cd488e706fdfe0552ce44c5802a538dfd61c0/src/Index.ts#L197)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> Could probably use _.extend here http://underscorejs.org/#extend
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/74)*

**Pull request merged**
