### PR TITLE
Added check to support adding jQuery after the jsSearch

### PR DESCRIPTION
**Pull request by mcarpentierCoveo**
https://coveord.atlassian.net/browse/JSUI-887

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/48)

### CODE REVIEW

**Comment by olamothe** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Base/CoveoJQuery.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/48#-KLXkC4jp67t7L3bqhx4:-KLXkC4jp67t7L3bqhx5:442753644) ([raw file](https://github.com/coveo/search-ui/blob/732dccdf57d042ea9fc44a56e0c3267763cded39/src/ui/Base/CoveoJQuery.ts#L29)):*
> ```XML
> 
> function initCoveoJQuery(){
>   jQueryInstance = window['$'];
> ```

Humm, thinking about this, I would add one more sanity check here to check that window['$'] is actually jQuery and not Prototype js or any other lib that use $ as a variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/48#-:-KLXkQmSPeG0vLCCRaWM:1417088721)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Base/CoveoJQuery.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/48#-KLXkC4jp67t7L3bqhx4:-KLXoxN7wWMJy7XKcYgs:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/732dccdf57d042ea9fc44a56e0c3267763cded39/src/ui/Base/CoveoJQuery.ts#L29)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Humm, thinking about this, I would add one more sanity check here to check that window['$'] is actually jQuery and not Prototype js or any other lib that use $ as a variable.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/48)*

**Comment by olamothe** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/48)*

**Comment by mcarpentierCoveo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/48)*

**Pull request merged**
