### PR TITLE
*fixes current tab exception

### PR DESCRIPTION
**Pull request by sbelzile-Coveo**
https://coveord.atlassian.net/browse/JSUI-991

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/120)

### CODE REVIEW

**Comment by olamothe** [comment]
:lgtm: 

A new UT to check this would have been interesting.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/120#-:-KNrgiV2Mh4nvmM0gm6x:1128831445)*

**Comment by dms1lva** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/ui/CurrentTab/CurrentTab.ts, line 43 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/120#-KO64H5TCi2wG_mhW-yn:-KO64H5UTvHDacDVjl-s:-1382232008) ([raw file](https://github.com/coveo/search-ui/blob/6df082291f3f4c445fd0c9c4231b8d09e3dc4d4c/src/ui/CurrentTab/CurrentTab.ts#L43)):*
> ```XML
>     this.bind.onRootElement(eventName, this.handleTabChange);
>     if (this.options.tabSectionToOpen) {
>       var tabSection = $$(this.root).find(this.options.tabSectionToOpen);
> ```

I'm curious to know why you changed `let` to `var`.

---

*[test/ui/CurrentTabTest.ts, line 45 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/120#-KO68zcxVQrDFyn3nlHk:-KO68zcxVQrDFyn3nlHl:448468447) ([raw file](https://github.com/coveo/search-ui/blob/6df082291f3f4c445fd0c9c4231b8d09e3dc4d4c/test/ui/CurrentTabTest.ts#L45)):*
> ```XML
> 
>     it('does not explode when a tab section to open is defined and no element has class coveo-glass', () => {
>       let el = document.createElement('div');
> ```

You could do `$$('div')` instead. Also valid for the elements you created using `document.createElement` below.

---

*[test/ui/CurrentTabTest.ts, line 47 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/120#-KO68T0LBwahuvAdS1hA:-KO68T0LBwahuvAdS1hB:1197795520) ([raw file](https://github.com/coveo/search-ui/blob/6df082291f3f4c445fd0c9c4231b8d09e3dc4d4c/test/ui/CurrentTabTest.ts#L47)):*
> ```XML
>       let el = document.createElement('div');
> 
>       let tabSection = document.createElement('div');
> ```

Here you could do `$$('div', {className: 'tabSection'});`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/120)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/ui/CurrentTab/CurrentTab.ts, line 43 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/120#-KO64H5TCi2wG_mhW-yn:-KO6A-is9YAHAGxd67Y0:-1197924827) ([raw file](https://github.com/coveo/search-ui/blob/6df082291f3f4c445fd0c9c4231b8d09e3dc4d4c/src/ui/CurrentTab/CurrentTab.ts#L43)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> I'm curious to know why you changed `let` to `var`.
</details>
Ahh I guess you did it because there's vars everywhere in this class. We're transition to the use of `let`. You can change them to `var` to `let` when you see some :grinning: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/120)*

**Comment by sbelzile-Coveo** [comment]
*[src/ui/CurrentTab/CurrentTab.ts, line 43 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/120#-KO64H5TCi2wG_mhW-yn:-KO6AI9jCAi1V6KERyyM:-194880264) ([raw file](https://github.com/coveo/search-ui/blob/6df082291f3f4c445fd0c9c4231b8d09e3dc4d4c/src/ui/CurrentTab/CurrentTab.ts#L43)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> Ahh I guess you did it because there's vars everywhere in this class. We're transition to the use of `let`. You can change them to `var` to `let` when you see some :grinning: 
</details>
"We're transition to the use of let" -> any reason to this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/120)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/ui/CurrentTab/CurrentTab.ts, line 43 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/120#-KO64H5TCi2wG_mhW-yn:-KO6BF16CB6yEGnkjDcr:1415433710) ([raw file](https://github.com/coveo/search-ui/blob/6df082291f3f4c445fd0c9c4231b8d09e3dc4d4c/src/ui/CurrentTab/CurrentTab.ts#L43)):*
<details><summary><i>Previously, sbelzile-Coveo wrote…</i></summary>
> "We're transition to the use of let" -> any reason to this?
</details>
`let` supports block scope declaration which is way less confusing compared to `var`. https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/120)*

**Comment by dms1lva** [comment]
:lgtm: Thanks! Can you merge master in your branch?

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/120#-:-KO6KPcj-m38J9EMHKor:178226877)*

**Pull request merged**
