### PR TITLE
Jsui 873

### PR DESCRIPTION
**Pull request by dms1lva**
Body margin was offsetting the popup position. Fixed by subtracting the body margin when getting the element position in pop up utils.

@olamothe Ended up doing as you suggested. I guess I really wanted to bang my head against bootstrap/jquery code. Still curious to understand why their stuff works 😝

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/52)

### CODE REVIEW

**Comment by olamothe** [comment]
:lgtm:

Did you check the behavior in safari/firefox/IE Edge ?

It should be okay, but just to make sure.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/52#-:-KLqYRZQ7vxCk1-NGKqI:-332776990)*

**Comment by dms1lva** [comment]
No I didn't. What do we use to test IE? I remember there was a website to do that but don't remember the name.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/52#-:-KLqYqoAbEfjzoWsEaRg:-92961589)*

**Comment by olamothe** [comment]
We have a browser stack account. Ask Cedric for access. Also, don't forget to graft the fix in the july branch.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/52#-:-KLrFJadDHmubXPJeRwQ:-280156892)*

**Comment by olamothe** [comment]
:lgtm: Ship it.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/52#-:-KM-KIcHoZey68Ql_8W5:-1559441138)*

**Pull request merged**
