### PR TITLE
JSUI-862 - ResultLayout

### PR DESCRIPTION
**Pull request by Dominionized**
EARLY PULL REQUEST

This implements additional result layouts.
- Multiple `ResultList`s can now be present in the page, each with its own data-layout (currently can be "list", "card" or "table")
- A new `ResultLayout` component has been created, which calls a populate event, which is then catched by the `ResultList`s which add themselves to the available layout.

[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

---

This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/144)

### CODE REVIEW

**Comment by olamothe** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/events/ResultLayoutEvents.ts, line 5 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYILCZr4ztFj1lx-AC:-KPYILCZr4ztFj1lx-AD:b-4a30u3) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/events/ResultLayoutEvents.ts#L5)):*
> ```XML
> }
> export class ResultLayoutEvents {
>   public static resultLayoutPopulate = 'resultLayoutPopulate';
> ```

I prefer `populateResultLayout`, to mimick the `BreadcrumbEvents`

---

*[src/ui/ResultLayout/ResultLayout.ts, line 43 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYIuYClWSADtiHWnhd:-KPYIuYDR88PVD9IWi8e:b7pz2xy) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultLayout/ResultLayout.ts#L43)):*
> ```XML
>     this.buttons = {};
> 
>     const eventName = this.queryStateModel.getEventName(Model.eventTypes.changeOne) + QueryStateModel.attributesEnum.layout;
> ```

This is what the "older" code was using.

Instead you can do this inside a component : 

`this.bind.onQueryState(MODEL_EVENTS.CHANGE_ONE, QUERY_STATE_ATTRIBUTES.LAYOUT, ()=>{})`

If you see any older code that still use this method feel free to change it to the newer one.

---

*[src/ui/ResultLayout/ResultLayout.ts, line 57 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYJhJxKO1t7Cc-vXIQ:-KPYJhJyQ8sfIRoh5oMh:beedm1f) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultLayout/ResultLayout.ts#L57)):*
> ```XML
>    * @param layout The new layout. Available values are `list`, `card` and `table`.
>    */
>   public changeLayout(layout: string) {
> ```

You can use string literal here. It's new in typescript 1.8.

 You can create a `type ValidLayout = 'list' | 'card' | 'table'`, then the method would become `public changeLayout(layout: ValidLayout)`

---

*[src/ui/ResultLayout/ResultLayout.ts, line 142 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYKRhiRilnrUherfpe:-KPYKRhiRilnrUherfpf:b6qnb9i) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultLayout/ResultLayout.ts#L142)):*
> ```XML
>   }
> 
>   private getQsmValue(): string {
> ```

Cool name, but we never use it anywhere else in the code :)

I would change it to simply `getModelValue`

---

*[src/ui/ResultList/ResultList.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYLNCTsFF7HZleVo7T:-KPYLNCTsFF7HZleVo7U:b-9t6u93) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultList/ResultList.ts#L130)):*
> ```XML
> 
>   public static resultCurrentlyBeingRendered: IQueryResult = null;
>   public static currentLayout: string;
> ```

Hum, we cannot use a static variable for this.

This means that if we have 2 different interface or one interface displaying multiple result list (which could be a very valid use case), they are all forced to use the same layout.

---

*[templates/conditions.json, line 4 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYLei4-V4ntpb03IXz:-KPYLei4-V4ntpb03IY-:b9fv9n5) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/templates/conditions.json#L4)):*
> ```JSON
>   "MobileChatter": {
>     "priority": 2,
>     "value": "(raw.objecttype =='FeedItem' || raw.objecttype == 'FeedComment') && (Coveo.DeviceUtils.isSmallScreenWidth() || Coveo.ResultList.currentLayout === 'card')"
> ```

As I said with my comment regarding the multiple result list problem, we cannot do this.

We should probably implement the required code either in the result list component or the Template class itself. I'm not sure which, but it certainly cannot be a static value like this set directly on the condition of the template.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/144)*

**Comment by Dominionized** [comment]
Review status: 13 of 37 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/events/ResultLayoutEvents.ts, line 5 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYILCZr4ztFj1lx-AC:-KQ5ytPyVdSsD_dZFJR6:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/events/ResultLayoutEvents.ts#L5)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> I prefer `populateResultLayout`, to mimick the `BreadcrumbEvents`
</details>
Done.

---

*[src/ui/ResultLayout/ResultLayout.ts, line 43 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYIuYClWSADtiHWnhd:-KQ6-oPwfJ4a9T9RIg9c:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultLayout/ResultLayout.ts#L43)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> This is what the "older" code was using.
> 
> Instead you can do this inside a component : 
> 
> `this.bind.onQueryState(MODEL_EVENTS.CHANGE_ONE, QUERY_STATE_ATTRIBUTES.LAYOUT, ()=>{})`
> 
> If you see any older code that still use this method feel free to change it to the newer one.
</details>
Done.

---

*[src/ui/ResultLayout/ResultLayout.ts, line 57 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYJhJxKO1t7Cc-vXIQ:-KQ60YdMIlkEhU7uw_CP:bh4c8ya) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultLayout/ResultLayout.ts#L57)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> You can use string literal here. It's new in typescript 1.8.
> 
>  You can create a `type ValidLayout = 'list' | 'card' | 'table'`, then the method would become `public changeLayout(layout: ValidLayout)`
</details>
Done. I added a `ValidLayout` type while still having the string array for runtime validation.

---

*[src/ui/ResultLayout/ResultLayout.ts, line 142 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYKRhiRilnrUherfpe:-KQ601QVkW0Cfn5cFFoc:b-896fix) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultLayout/ResultLayout.ts#L142)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Cool name, but we never use it anywhere else in the code :)
> 
> I would change it to simply `getModelValue`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/144)*

**Comment by Dominionized** [comment]
Review status: 12 of 40 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ui/ResultList/ResultList.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KPYLNCTsFF7HZleVo7T:-KQLp7AGo4Zgmx7CpmtX:b-vpalb6) ([raw file](https://github.com/coveo/search-ui/blob/b733535da388658c60934efef39fd70bfdb4067f/src/ui/ResultList/ResultList.ts#L130)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Hum, we cannot use a static variable for this.
> 
> This means that if we have 2 different interface or one interface displaying multiple result list (which could be a very valid use case), they are all forced to use the same layout.
</details>
Done. I added an `options` parameter when instantiating templates that the conditions go pick up and render accordingly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/144)*

**Comment by Dominionized** [comment]
Reviewed 1 of 28 files at r2.
Review status: 13 of 40 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/144)*

**Comment by Dominionized** [comment]
Reviewed 1 of 28 files at r2, 1 of 4 files at r3.
Review status: 15 of 40 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/ui/Templates/Template.ts, line 42 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/144#-KQLybLPXTnTRpgSoQM2:-KQLybLPXTnTRpgSoQM3:bgtj8mw) ([raw file](https://github.com/coveo/search-ui/blob/230b160f61db640e9db92228b49d21c2553ec5ba/src/ui/Templates/Template.ts#L42)):*
> ```XML
>   instantiateToString(object?: any, checkCondition = true, options?: ITemplateOptions): string {
>     if (options) {
>       object.options = options;
> ```

Question : is this susceptible to collide with an index field ? This is the simplest method that I found to do it, but if it causes a problem, it'll need to be changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/144)*

**Comment by olamothe** [comment]
As discussed in our meeting, we will re=open a clean PR for this issue once the work is done.

**Pull request closed without merging**
