### PR TITLE
Make the .Dependencies file obsolete.

### PR DESCRIPTION
**Pull request by olamothe**
Use various webpack plugins and loader to make the .Dependencies file obsolete.

https://coveord.atlassian.net/browse/JSUI-939

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/96)

### CODE REVIEW

**Comment by Dominionized** [comment]
Review status: 0 of 78 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Dependencies.js, line 1 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/96#-KN42Om_sHsf-97NNi6x:-KN42Om_sHsf-97NNi6y:1438086484) ([raw file](https://github.com/coveo/search-ui/blob/cb3f75d2a549e3904c9994bd742eb96f51ce046d/src/Dependencies.js#L1)):*
> ```JavaScript
> // This file is there for legacy reason only. (So that we do not 404 on every page that request this file)
> ```

every page that request**s** this file

---

*[src/ui/Facet/BreadcrumbValuesList.ts, line 8 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/96#-KN4376K0QTYvWQ8ZdY0:-KN4376K0QTYvWQ8ZdY1:-1722793996) ([raw file](https://github.com/coveo/search-ui/blob/cb3f75d2a549e3904c9994bd742eb96f51ce046d/src/ui/Facet/BreadcrumbValuesList.ts#L8)):*
> ```XML
> import {l} from '../../strings/Strings';
> import {$$} from '../../utils/Dom';
> import Globalize = require('globalize');
> ```

Shouldn't we use ES6 syntax here ?
`import * as Globalize from 'globalize';`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/96)*

**Comment by Dominionized** [comment]
Reviewed 78 of 78 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/96)*

**Comment by dms1lva** [comment]
:lgtm:

---

Reviewed 78 of 78 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/96#-:-KN8fDTFxWfv8dpyf6v4:1417088721)*

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Reviewed 78 of 78 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/96#-:-KN90V3HEwQdHGdX_c_3:1417088721)*

**Pull request merged**
