### PR TITLE
ResponsiveFacets - Fix d3.js error with facet slider graph

### PR DESCRIPTION
**Pull request by dms1lva**
https://coveord.atlassian.net/browse/JSUI-927

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/95)

### CODE REVIEW

**Comment by olamothe** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ui/FacetSlider/FacetSlider.ts, line 298 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzTxXJTtcJRrQMzFxY:-KMzTxXJTtcJRrQMzFxZ:54696755) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/FacetSlider/FacetSlider.ts#L298)):*
> ```XML
> 
>   /**
>    * There is delayed graph data if at the time the facet slider tried to draw, graph data was undefined or the facet was hidden in the
> ```

Meh, the JS doc we add serves for user interacting with the framework, to generate the API reference.

This really is a method for internal pruposes only, I would not document it publicly like this.

---

*[src/ui/FacetSlider/FacetSlider.ts, line 302 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzTsqCGMKFjLrzY1Us:-KMzTsqCGMKFjLrzY1Ut:-510407393) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/FacetSlider/FacetSlider.ts#L302)):*
> ```XML
>    */
>   public drawDelayedGraphData() {
>     debugger;
> ```

:-1: 

---

*[src/ui/FacetSlider/FacetSlider.ts, line 557 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzUO3LEOIa_9e5KoIK:-KMzUO3LEOIa_9e5KoIL:-1495609414) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/FacetSlider/FacetSlider.ts#L557)):*
> ```XML
> 
>   private isFacetDropdownHidden() {
>     let facetDropdown = document.querySelector('.coveo-facet-column');
> ```

Everytime you reference document or some global object, **really** think if you absolutely need this.

In this case, you should search from the root of the interface, not globally.

---

*[src/ui/Misc/Slider.ts, line 653 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzXfrkyvts4-kEKd7A:-KMzXfrkyvts4-kEKd7B:1429671183) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/Misc/Slider.ts#L653)):*
> ```XML
>   }
> 
>   public draw(data: ISliderGraphData[] = this.oldData, forceDraw: boolean = false) {
> ```

Mehh, this looks like a hack.

I think Slider should not bother with the size of the interface, it should always draw when the public method is called.

Move the logic to call draw or not in the FacetSlider itself, it's the one that should decide wether to draw or not depending on it's state.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 169 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzWvIjMckThxOHTkLs:-KMzWvIjMckThxOHTkLt:-509658578) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L169)):*
> ```XML
>   private openDropdown() {
>     this.positionPopup();
>     document.documentElement.appendChild(this.popupBackground.el);
> ```

This cause issue in certain scenario : Since the background use position fixed 0 0 0 0, add it to the root of the search interface. It's much less polluting for the global page content.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 207 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzWJ3knqSsEMPtkzky:-KMzWJ3knqSsEMPtkzkz:549236513) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L207)):*
> ```XML
>   private cleanUpDropdown() {
>     this.dropdownHeader.detach();
>     let facetList = this.dropdownContent.findAll('.CoveoFacet');
> ```

Use `Component.computeCssClassNameForType`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95)*

**Comment by olamothe** [comment]
Reviewed 7 of 9 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ui/Misc/Slider.ts, line 653 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzXfrkyvts4-kEKd7A:-KMzYrtXwTFFiMpA8N3y:67445263) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/Misc/Slider.ts#L653)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Mehh, this looks like a hack.
> 
> I think Slider should not bother with the size of the interface, it should always draw when the public method is called.
> 
> Move the logic to call draw or not in the FacetSlider itself, it's the one that should decide wether to draw or not depending on it's state.
</details>
Since Slider draws on resize, I need to restrain it from drawing when the interface is in small mode. However, I also need it to draw when the facet dropdown is opened. So if I call draw on the Slider from the facet when the facet dropdown is opened, it will not draw because the interface is in small mode. I had two choice:
- Verify if the facet dropdown is hidden or not directly from the Slider. I thought this was bad because it added to Slider the knowledge of the facet dropdown which doesn't make sense.
- Bind the resize event in the facet slider class. I don't like this because if the Slider is used elsewhere, the component that uses it will also need to bind the resize event, even if its the Slider's job.
- Force it to draw via a parameter when the facet dropdown is opened.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ui/FacetSlider/FacetSlider.ts, line 298 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzTxXJTtcJRrQMzFxY:-KN7ZjrFvTR94wJSyrQm:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/FacetSlider/FacetSlider.ts#L298)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Meh, the JS doc we add serves for user interacting with the framework, to generate the API reference.
> 
> This really is a method for internal pruposes only, I would not document it publicly like this.
</details>
Done.

---

*[src/ui/FacetSlider/FacetSlider.ts, line 302 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzTsqCGMKFjLrzY1Us:-KN7ZkE_b0gBUFH3bjl9:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/FacetSlider/FacetSlider.ts#L302)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> :-1: 
</details>
Done.

---

*[src/ui/FacetSlider/FacetSlider.ts, line 557 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzUO3LEOIa_9e5KoIK:-KN7ZtYb1fNyqB52Ozmq:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/FacetSlider/FacetSlider.ts#L557)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Everytime you reference document or some global object, **really** think if you absolutely need this.
> 
> In this case, you should search from the root of the interface, not globally.
</details>
Done.

---

*[src/ui/Misc/Slider.ts, line 653 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzXfrkyvts4-kEKd7A:-KN7ZwnS4kU22pwxpaMD:-1956929720) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/Misc/Slider.ts#L653)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> Since Slider draws on resize, I need to restrain it from drawing when the interface is in small mode. However, I also need it to draw when the facet dropdown is opened. So if I call draw on the Slider from the facet when the facet dropdown is opened, it will not draw because the interface is in small mode. I had two choice:
> - Verify if the facet dropdown is hidden or not directly from the Slider. I thought this was bad because it added to Slider the knowledge of the facet dropdown which doesn't make sense.
> - Bind the resize event in the facet slider class. I don't like this because if the Slider is used elsewhere, the component that uses it will also need to bind the resize event, even if its the Slider's job.
> - Force it to draw via a parameter when the facet dropdown is opened.
</details>
What do you guys think is the best solution?

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 169 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzWvIjMckThxOHTkLs:-KN7_0e3HvQ2u6vaPn67:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L169)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> This cause issue in certain scenario : Since the background use position fixed 0 0 0 0, add it to the root of the search interface. It's much less polluting for the global page content.
</details>
Done.

---

*[src/ui/ResponsiveComponents/ResponsiveFacets.ts, line 207 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzWJ3knqSsEMPtkzky:-KN7hcRilEVoItRB6YmE:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/ResponsiveComponents/ResponsiveFacets.ts#L207)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> Use `Component.computeCssClassNameForType`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95)*

**Comment by olamothe** [comment]
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ui/Misc/Slider.ts, line 653 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzXfrkyvts4-kEKd7A:-KN8aDyGro34j4zU5-VV:185823091) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/Misc/Slider.ts#L653)):*
<details><summary><i>Previously, dms1lva (Dario Martins Silva) wrote…</i></summary>
> What do you guys think is the best solution?
</details>
I think #2 is the best option.

I don't agree that it's the slider job to handle the resize. For example, if the Slider is displayed in a component inside the result list, it won't need to bother with the facet dropdown menu.

So I think it's okay for the whole logic to be handled in the FacetSlider class, since it's the one that is rendered in that particular "facet dropdown", and it won't always be the case if we reuse the Slider elsewhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95)*

**Comment by olamothe** [comment]
:lgtm:

---

Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95#-:-KN8ana2KDm6IQtTXbcV:1417088721)*

**Comment by olamothe** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95)*

**Comment by dms1lva** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/ui/Misc/Slider.ts, line 653 \[r3\]](https://reviewable.io:443/reviews/coveo/search-ui/95#-KMzXfrkyvts4-kEKd7A:-KN9Ha53dpNzAu6oud18:-499146009) ([raw file](https://github.com/coveo/search-ui/blob/b64d7ef6072d147966354919eb7d65a52bc336ef/src/ui/Misc/Slider.ts#L653)):*
<details><summary><i>Previously, olamothe (Olivier Lamothe) wrote…</i></summary>
> I think #2 is the best option.
> 
> I don't agree that it's the slider job to handle the resize. For example, if the Slider is displayed in a component inside the result list, it won't need to bother with the facet dropdown menu.
> 
> So I think it's okay for the whole logic to be handled in the FacetSlider class, since it's the one that is rendered in that particular "facet dropdown", and it won't always be the case if we reuse the Slider elsewhere.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/95)*

**Pull request merged**
