### PR TITLE
Update / Revision for generated documentation

### PR DESCRIPTION
**Pull request by vlarocque**
[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/156)

### CODE REVIEW

**Comment by olamothe** [comment]
Looks okay so far !

---

Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/156#-:-KQ2_NPHOj2GVt_uBSdb:b-c8y0sx)*

**Comment by ccgagnon** [comment]
Reviewed 37 of 37 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ui/FacetSlider/FacetSlider.ts, line 155 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/156#-KQ7K3mi9tXSzxumvRwa:-KQ7K3mkJ1Kh3SJ_ANJv:b44mxxl) ([raw file](https://github.com/coveo/search-ui/blob/2d28efe2ae9fee4fbf1d3882a586107c30a2dd4b/src/ui/FacetSlider/FacetSlider.ts#L155)):*
> ```XML
>      *   <li>enable : (data-display-as-value-enable) <code>boolean</code> : Specifies whether the caption should be displayed as a value or not. Default is <code>true</code></li>.
>      *   <li>unitSign : (data-display-as-value-unit-sign) <code>string</code> : Specifies the unit sign for this value.</li>
>      *   <li>separator : (data-display-as-value-separator) <code>string</code> : Specifies the character(s) to use as a separator in the caption. Default is `-.</li>`.
> ```

did you mean `-`.</li> instead of `-.</li>`

---

*[src/ui/FacetSlider/FacetSlider.ts, line 183 \[r2\]](https://reviewable.io:443/reviews/coveo/search-ui/156#-KQ7Kn9HXaK1xaDtEUUY:-KQ7Kn9IF3xk3kRiwQ5t:buo9nmt) ([raw file](https://github.com/coveo/search-ui/blob/2d28efe2ae9fee4fbf1d3882a586107c30a2dd4b/src/ui/FacetSlider/FacetSlider.ts#L183)):*
> ```XML
>      * Available options are :
>      *
>      *   <li>steps: (data-graph-steps) <code>number</code> : Specifies the number of steps/columns to display in your graph. The default value is `10</li>`.
> ```

Same here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/156)*

**Comment by ccgagnon** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/156)*

**Comment by ccgagnon** [comment]
Looks good to me! Ship it!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/156#-:-KQ7kYlb-C0sXAs2jKrt:b-qggh50)*

**Comment by ccgagnon** [comment]
Reviewed 23 of 29 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/156)*

**Pull request merged**
