### PR TITLE
Clicking the setting button now closes the menu if it's opened. https…

### PR DESCRIPTION
**Pull request by fgagnoncoveo**
[Deploy](https://dashboard.heroku.com/pipelines/a3535101-5bbf-4a5b-a909-47fcf8c9f149)
…://coveord.atlassian.net/browse/JSUI-1019

---
This change is [Reviewable](https://reviewable.io/reviews/coveo/search-ui/135)

### CODE REVIEW

**Comment by Dominionized** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Settings/Settings.ts, line 94 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/135#-KOpkXg02RAYRXi6MbU0:-KOpkXg02RAYRXi6MbU1:b-ka47li) ([raw file](https://github.com/coveo/search-ui/blob/e87beef9b5a1aac0085accb90f170cf105448d72/src/ui/Settings/Settings.ts#L94)):*
> ```XML
> 
>     $$(this.element).on('click', () => {
>       if (this.isOpened) {
> ```

Duh, you missed an opportunity to make an awesome hackerz one-liner
`this.isOpened ? this.close() : this.open()` :stuck_out_tongue_winking_eye: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/135)*

**Comment by Dominionized** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/135#-:-KOpkoDY08DMfqb9f7nx:bnfp4nl)*

**Comment by fgagnoncoveo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Settings/Settings.ts, line 94 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/135#-KOpkXg02RAYRXi6MbU0:-KOpoQCzK7v4OSjg3X34:bcmg8oz) ([raw file](https://github.com/coveo/search-ui/blob/e87beef9b5a1aac0085accb90f170cf105448d72/src/ui/Settings/Settings.ts#L94)):*
<details><summary><i>Previously, Dominionized (Dominique Bégin) wrote…</i></summary>
> Duh, you missed an opportunity to make an awesome hackerz one-liner
> `this.isOpened ? this.close() : this.open()` :stuck_out_tongue_winking_eye: 
</details>
Thought about it, I always wonder if I should do it since it's (IMO) less readable. Granted this one is super simple!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/135)*

**Comment by Dominionized** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/ui/Settings/Settings.ts, line 94 \[r1\]](https://reviewable.io:443/reviews/coveo/search-ui/135#-KOpkXg02RAYRXi6MbU0:-KOq8cqwjhyD1Jioq7yJ:baxdnia) ([raw file](https://github.com/coveo/search-ui/blob/e87beef9b5a1aac0085accb90f170cf105448d72/src/ui/Settings/Settings.ts#L94)):*
<details><summary><i>Previously, fgagnoncoveo (François Gagnon) wrote…</i></summary>
> Thought about it, I always wonder if I should do it since it's (IMO) less readable. Granted this one is super simple!
</details>
I think in this case it looks pretty good and readable. In some cases it's definitely not the right choice though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/135)*

**Comment by mcarpentierCoveo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/coveo/search-ui/135#-:-KOv8SXLdhqpYJ22z5rD:bnfp4nl)*

**Pull request merged**
